test-regular:
  stage: test
  script:
    - make clean
    - make
    - ./utils/forced-tty-session ./bin/idio test

test-coverage:
  stage: test
  script:
    - make clean
    - make coverage
    - ./utils/forced-tty-session ./bin/idio test
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    reports:
      cobertura: coverage.xml

