build-regular:
  stage: build
  script:
    - make clean
    - make
  artifacts:
    paths:
    - bin/idio

test-regular:
  stage: test
  script:
    - ./utils/forced-tty-session ./bin/idio test
  needs: [build-regular]

build-coverage:
  stage: build
  script:
    - make clean
    - make coverage
  artifacts:
    paths:
    - bin/idio
  needs: [test-regular]

test-coverage:
  stage: test
  script:
    - ./utils/forced-tty-session ./bin/idio test
    - gcovr --xml-pretty --exclude-unreachable-branches --print-summary -o coverage.xml --root ${CI_PROJECT_DIR}
  coverage: /^\s*lines:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    reports:
      cobertura: build/coverage.xml
  needs: [build-coverage]

