build-regular:
  stage: build
  script:
    - make clean
    - make

test-regular:
  stage: test
  script:
    - make test
  needs: [build-regular]

build-coverage:
  stage: build
  script:
    - make clean
    - make coverage

test-coverage:
  stage: test
  script:
    - make test
  needs: [build-coverage]

