
/*
 * libc-api.h
 *
 *
 * This file was generated by c-api-gen on a Linux 5.10.15-200.fc33.x86_64 x86_64 system
 */

#ifndef LIBC_API_H
#define LIBC_API_H


/*
 * For reference, this system/API uses these base_types:
 *
 * unsigned char                   1 bytes
 * short unsigned int              2 bytes
 * unsigned int                    4 bytes
 * long unsigned int               8 bytes
 * signed char                     1 bytes
 * short int                       2 bytes
 * int                             4 bytes
 * long int                        8 bytes
 * char                            1 bytes
 * long long unsigned int          8 bytes
 * long long int                   8 bytes
 * float                           4 bytes
 * double                          8 bytes

 *
 * Pointer size                    8 bytes
*/


#define IDIO_USER_libc_TYPE_ASSERT(t,x)	{						\
	if (! idio_isa_libc_ ## t (x)) {						\
	    idio_error_param_type_C ("libc/" #t, x, __FILE__, __func__, __LINE__);	\
	}										\
    }

/* /usr/include/bits/types.h */
#define idio_libc___ssize_t                 idio_C_long
#define IDIO_C_TYPE_libc___ssize_t          IDIO_C_TYPE_long
#define idio_isa_libc___ssize_t             idio_isa_C_long

/* /usr/include/sys/types.h */
#define idio_libc_ssize_t                   idio_libc___ssize_t
#define IDIO_C_TYPE_libc_ssize_t            IDIO_C_TYPE_libc___ssize_t
#define idio_isa_libc_ssize_t               idio_isa_libc___ssize_t

/* /usr/lib/gcc/x86_64-redhat-linux/10/include/stddef.h */
#define idio_libc_size_t                    idio_C_ulong
#define IDIO_C_TYPE_libc_size_t             IDIO_C_TYPE_ulong
#define idio_isa_libc_size_t                idio_isa_C_ulong

/* /usr/include/bits/types.h */
#define idio_libc___pid_t                   idio_C_int
#define IDIO_C_TYPE_libc___pid_t            IDIO_C_TYPE_int
#define idio_isa_libc___pid_t               idio_isa_C_int

#define idio_libc___clock_t                 idio_C_long
#define IDIO_C_TYPE_libc___clock_t          IDIO_C_TYPE_long
#define idio_isa_libc___clock_t             idio_isa_C_long

/* /usr/include/bits/types/clock_t.h */
#define idio_libc_clock_t                   idio_libc___clock_t
#define IDIO_C_TYPE_libc_clock_t            IDIO_C_TYPE_libc___clock_t
#define idio_isa_libc_clock_t               idio_isa_libc___clock_t

/* /usr/include/bits/termios.h */
#define idio_libc_tcflag_t                  idio_C_uint
#define IDIO_C_TYPE_libc_tcflag_t           IDIO_C_TYPE_uint
#define idio_isa_libc_tcflag_t              idio_isa_C_uint

#define idio_libc_cc_t                      idio_C_uchar
#define IDIO_C_TYPE_libc_cc_t               IDIO_C_TYPE_uchar
#define idio_isa_libc_cc_t                  idio_isa_C_uchar

#define idio_libc_speed_t                   idio_C_uint
#define IDIO_C_TYPE_libc_speed_t            IDIO_C_TYPE_uint
#define idio_isa_libc_speed_t               idio_isa_C_uint

/* /usr/include/bits/types.h */
#define idio_libc___dev_t                   idio_C_ulong
#define IDIO_C_TYPE_libc___dev_t            IDIO_C_TYPE_ulong
#define idio_isa_libc___dev_t               idio_isa_C_ulong

#define idio_libc___ino_t                   idio_C_ulong
#define IDIO_C_TYPE_libc___ino_t            IDIO_C_TYPE_ulong
#define idio_isa_libc___ino_t               idio_isa_C_ulong

#define idio_libc___nlink_t                 idio_C_ulong
#define IDIO_C_TYPE_libc___nlink_t          IDIO_C_TYPE_ulong
#define idio_isa_libc___nlink_t             idio_isa_C_ulong

#define idio_libc___mode_t                  idio_C_uint
#define IDIO_C_TYPE_libc___mode_t           IDIO_C_TYPE_uint
#define idio_isa_libc___mode_t              idio_isa_C_uint

#define idio_libc___uid_t                   idio_C_uint
#define IDIO_C_TYPE_libc___uid_t            IDIO_C_TYPE_uint
#define idio_isa_libc___uid_t               idio_isa_C_uint

#define idio_libc___gid_t                   idio_C_uint
#define IDIO_C_TYPE_libc___gid_t            IDIO_C_TYPE_uint
#define idio_isa_libc___gid_t               idio_isa_C_uint

#define idio_libc___off_t                   idio_C_long
#define IDIO_C_TYPE_libc___off_t            IDIO_C_TYPE_long
#define idio_isa_libc___off_t               idio_isa_C_long

#define idio_libc___blksize_t               idio_C_long
#define IDIO_C_TYPE_libc___blksize_t        IDIO_C_TYPE_long
#define idio_isa_libc___blksize_t           idio_isa_C_long

#define idio_libc___blkcnt_t                idio_C_long
#define IDIO_C_TYPE_libc___blkcnt_t         IDIO_C_TYPE_long
#define idio_isa_libc___blkcnt_t            idio_isa_C_long

#define idio_libc___time_t                  idio_C_long
#define IDIO_C_TYPE_libc___time_t           IDIO_C_TYPE_long
#define idio_isa_libc___time_t              idio_isa_C_long

#define idio_libc___syscall_slong_t         idio_C_long
#define IDIO_C_TYPE_libc___syscall_slong_t  IDIO_C_TYPE_long
#define idio_isa_libc___syscall_slong_t     idio_isa_C_long

/* /usr/include/sys/resource.h */
#define idio_libc___rlimit_resource_t       idio_C_uint
#define IDIO_C_TYPE_libc___rlimit_resource_t IDIO_C_TYPE_uint
#define idio_isa_libc___rlimit_resource_t   idio_isa_C_uint

/* /usr/include/bits/types.h */
#define idio_libc___rlim_t                  idio_C_ulong
#define IDIO_C_TYPE_libc___rlim_t           IDIO_C_TYPE_ulong
#define idio_isa_libc___rlim_t              idio_isa_C_ulong

/* /usr/include/bits/resource.h */
#define idio_libc_rlim_t                    idio_libc___rlim_t
#define IDIO_C_TYPE_libc_rlim_t             IDIO_C_TYPE_libc___rlim_t
#define idio_isa_libc_rlim_t                idio_isa_libc___rlim_t

/* /usr/include/bits/types.h */
#define idio_libc___suseconds_t             idio_C_long
#define IDIO_C_TYPE_libc___suseconds_t      IDIO_C_TYPE_long
#define idio_isa_libc___suseconds_t         idio_isa_C_long

/* /usr/include/sys/resource.h */
#define idio_libc___rusage_who_t            idio_C_int
#define IDIO_C_TYPE_libc___rusage_who_t     IDIO_C_TYPE_int
#define idio_isa_libc___rusage_who_t        idio_isa_C_int

/* /usr/include/bits/types.h */
#define idio_libc___intmax_t                idio_C_long
#define IDIO_C_TYPE_libc___intmax_t         IDIO_C_TYPE_long
#define idio_isa_libc___intmax_t            idio_isa_C_long

/* /usr/include/stdint.h */
#define idio_libc_intmax_t                  idio_libc___intmax_t
#define IDIO_C_TYPE_libc_intmax_t           IDIO_C_TYPE_libc___intmax_t
#define idio_isa_libc_intmax_t              idio_isa_libc___intmax_t

/* /usr/include/bits/types.h */
#define idio_libc___uintmax_t               idio_C_ulong
#define IDIO_C_TYPE_libc___uintmax_t        IDIO_C_TYPE_ulong
#define idio_isa_libc___uintmax_t           idio_isa_C_ulong

/* /usr/include/stdint.h */
#define idio_libc_uintmax_t                 idio_libc___uintmax_t
#define IDIO_C_TYPE_libc_uintmax_t          IDIO_C_TYPE_libc___uintmax_t
#define idio_isa_libc_uintmax_t             idio_isa_libc___uintmax_t

/* /usr/include/bits/types.h */
#define idio_libc___intptr_t                idio_C_long
#define IDIO_C_TYPE_libc___intptr_t         IDIO_C_TYPE_long
#define idio_isa_libc___intptr_t            idio_isa_C_long

/* /usr/include/unistd.h */
#define idio_libc_intptr_t                  idio_libc___intptr_t
#define IDIO_C_TYPE_libc_intptr_t           IDIO_C_TYPE_libc___intptr_t
#define idio_isa_libc_intptr_t              idio_isa_libc___intptr_t

/* /usr/include/sys/types.h */
#define idio_libc_pid_t                     idio_libc___pid_t
#define IDIO_C_TYPE_libc_pid_t              IDIO_C_TYPE_libc___pid_t
#define idio_isa_libc_pid_t                 idio_isa_libc___pid_t

/* /usr/include/bits/types/time_t.h */
#define idio_libc_time_t                    idio_libc___time_t
#define IDIO_C_TYPE_libc_time_t             IDIO_C_TYPE_libc___time_t
#define idio_isa_libc_time_t                idio_isa_libc___time_t

/* /usr/include/sys/types.h */
#define idio_libc_suseconds_t               idio_libc___suseconds_t
#define IDIO_C_TYPE_libc_suseconds_t        IDIO_C_TYPE_libc___suseconds_t
#define idio_isa_libc_suseconds_t           idio_isa_libc___suseconds_t

#define idio_libc_mode_t                    idio_libc___mode_t
#define IDIO_C_TYPE_libc_mode_t             IDIO_C_TYPE_libc___mode_t
#define idio_isa_libc_mode_t                idio_isa_libc___mode_t

#define idio_libc_dev_t                     idio_libc___dev_t
#define IDIO_C_TYPE_libc_dev_t              IDIO_C_TYPE_libc___dev_t
#define idio_isa_libc_dev_t                 idio_isa_libc___dev_t

#define idio_libc_ino_t                     idio_libc___ino_t
#define IDIO_C_TYPE_libc_ino_t              IDIO_C_TYPE_libc___ino_t
#define idio_isa_libc_ino_t                 idio_isa_libc___ino_t

#define idio_libc_nlink_t                   idio_libc___nlink_t
#define IDIO_C_TYPE_libc_nlink_t            IDIO_C_TYPE_libc___nlink_t
#define idio_isa_libc_nlink_t               idio_isa_libc___nlink_t

#define idio_libc_uid_t                     idio_libc___uid_t
#define IDIO_C_TYPE_libc_uid_t              IDIO_C_TYPE_libc___uid_t
#define idio_isa_libc_uid_t                 idio_isa_libc___uid_t

#define idio_libc_gid_t                     idio_libc___gid_t
#define IDIO_C_TYPE_libc_gid_t              IDIO_C_TYPE_libc___gid_t
#define idio_isa_libc_gid_t                 idio_isa_libc___gid_t

#define idio_libc_off_t                     idio_libc___off_t
#define IDIO_C_TYPE_libc_off_t              IDIO_C_TYPE_libc___off_t
#define idio_isa_libc_off_t                 idio_isa_libc___off_t

#define idio_libc_blksize_t                 idio_libc___blksize_t
#define IDIO_C_TYPE_libc_blksize_t          IDIO_C_TYPE_libc___blksize_t
#define idio_isa_libc_blksize_t             idio_isa_libc___blksize_t

#define idio_libc_blkcnt_t                  idio_libc___blkcnt_t
#define IDIO_C_TYPE_libc_blkcnt_t           IDIO_C_TYPE_libc___blkcnt_t
#define idio_isa_libc_blkcnt_t              idio_isa_libc___blkcnt_t



/* /usr/include/sys/utsname.h */
extern IDIO_SYMBOL_DECL (sysname);
extern IDIO_SYMBOL_DECL (nodename);
extern IDIO_SYMBOL_DECL (release);
extern IDIO_SYMBOL_DECL (version);
extern IDIO_SYMBOL_DECL (machine);
extern IDIO_SYMBOL_DECL (domainname);


/* /usr/include/sys/times.h */
extern IDIO_SYMBOL_DECL (tms_utime);
extern IDIO_SYMBOL_DECL (tms_stime);
extern IDIO_SYMBOL_DECL (tms_cutime);
extern IDIO_SYMBOL_DECL (tms_cstime);


/* /usr/include/bits/termios-struct.h */
extern IDIO_SYMBOL_DECL (c_iflag);
extern IDIO_SYMBOL_DECL (c_oflag);
extern IDIO_SYMBOL_DECL (c_cflag);
extern IDIO_SYMBOL_DECL (c_lflag);
extern IDIO_SYMBOL_DECL (c_line);
extern IDIO_SYMBOL_DECL (c_cc);
extern IDIO_SYMBOL_DECL (c_ispeed);
extern IDIO_SYMBOL_DECL (c_ospeed);


/* /usr/include/bits/stat.h */
extern IDIO_SYMBOL_DECL (st_dev);
extern IDIO_SYMBOL_DECL (st_ino);
extern IDIO_SYMBOL_DECL (st_nlink);
extern IDIO_SYMBOL_DECL (st_mode);
extern IDIO_SYMBOL_DECL (st_uid);
extern IDIO_SYMBOL_DECL (st_gid);
extern IDIO_SYMBOL_DECL (st_rdev);
extern IDIO_SYMBOL_DECL (st_size);
extern IDIO_SYMBOL_DECL (st_blksize);
extern IDIO_SYMBOL_DECL (st_blocks);
extern IDIO_SYMBOL_DECL (st_atim);
extern IDIO_SYMBOL_DECL (st_mtim);
extern IDIO_SYMBOL_DECL (st_ctim);


/* /usr/include/bits/types/struct_timespec.h */
extern IDIO_SYMBOL_DECL (tv_sec);
extern IDIO_SYMBOL_DECL (tv_nsec);


/* /usr/include/bits/sigaction.h */
extern IDIO_SYMBOL_DECL (__sigaction_handler);
extern IDIO_SYMBOL_DECL (sa_mask);
extern IDIO_SYMBOL_DECL (sa_flags);
extern IDIO_SYMBOL_DECL (sa_restorer);


/* /usr/include/bits/resource.h */
extern IDIO_SYMBOL_DECL (rlim_cur);
extern IDIO_SYMBOL_DECL (rlim_max);


/* /usr/include/bits/types/struct_timeval.h */
/* tv_sec already declared */
extern IDIO_SYMBOL_DECL (tv_usec);


/* /usr/include/bits/types/struct_rusage.h */
extern IDIO_SYMBOL_DECL (ru_utime);
extern IDIO_SYMBOL_DECL (ru_stime);

void idio_libc_api_add_primitives ();

void idio_init_libc_api ();

#endif /* LIBC_API_H */
