
/*
 * libc-api.h
 *
 *
 * This file was generated by idio-c-api-gen on a Linux 6.0.8-300.fc37.x86_64 x86_64 system
 */

#ifndef LIBC_API_H
#define LIBC_API_H


/*
 * For reference, this system/API uses these base_types:
 *
 * char                            1 bytes
 * signed char                     1 bytes
 * unsigned char                   1 bytes
 * short int                       2 bytes
 * short unsigned int              2 bytes
 * int                             4 bytes
 * float                           4 bytes
 * unsigned int                    4 bytes
 * double                          8 bytes
 * long int                        8 bytes
 * long long int                   8 bytes
 * long unsigned int               8 bytes
 * long long unsigned int          8 bytes
 *
 * Pointer size                    8 bytes
*/


#define IDIO_USER_libc_TYPE_ASSERT(t,x)	{						\
	if (! idio_isa_libc_ ## t (x)) {						\
	    idio_error_param_type_C ("libc/" #t, x, __FILE__, __func__, __LINE__);	\
	}										\
    }

/* /usr/include/bits/types.h */
#define IDIO_TYPE_C_libc___mode_t           IDIO_TYPE_C_UINT
#define idio_libc___mode_t                  idio_C_uint
#define IDIO_C_TYPE_libc___mode_t           IDIO_C_TYPE_uint
#define idio_isa_libc___mode_t              idio_isa_C_uint

#define IDIO_TYPE_C_libc___uid_t            IDIO_TYPE_C_UINT
#define idio_libc___uid_t                   idio_C_uint
#define IDIO_C_TYPE_libc___uid_t            IDIO_C_TYPE_uint
#define idio_isa_libc___uid_t               idio_isa_C_uint

#define IDIO_TYPE_C_libc___gid_t            IDIO_TYPE_C_UINT
#define idio_libc___gid_t                   idio_C_uint
#define IDIO_C_TYPE_libc___gid_t            IDIO_C_TYPE_uint
#define idio_isa_libc___gid_t               idio_isa_C_uint

#define IDIO_TYPE_C_libc___time_t           IDIO_TYPE_C_LONG
#define idio_libc___time_t                  idio_C_long
#define IDIO_C_TYPE_libc___time_t           IDIO_C_TYPE_long
#define idio_isa_libc___time_t              idio_isa_C_long

/* /usr/include/bits/types/time_t.h */
#define IDIO_TYPE_C_libc_time_t             IDIO_TYPE_C_libc___time_t
#define idio_libc_time_t                    idio_libc___time_t
#define IDIO_C_TYPE_libc_time_t             IDIO_C_TYPE_libc___time_t
#define idio_isa_libc_time_t                idio_isa_libc___time_t

/* /usr/include/bits/types.h */
#define IDIO_TYPE_C_libc___pid_t            IDIO_TYPE_C_INT
#define idio_libc___pid_t                   idio_C_int
#define IDIO_C_TYPE_libc___pid_t            IDIO_C_TYPE_int
#define idio_isa_libc___pid_t               idio_isa_C_int

#define IDIO_TYPE_C_libc___dev_t            IDIO_TYPE_C_ULONG
#define idio_libc___dev_t                   idio_C_ulong
#define IDIO_C_TYPE_libc___dev_t            IDIO_C_TYPE_ulong
#define idio_isa_libc___dev_t               idio_isa_C_ulong

#define IDIO_TYPE_C_libc___ino_t            IDIO_TYPE_C_ULONG
#define idio_libc___ino_t                   idio_C_ulong
#define IDIO_C_TYPE_libc___ino_t            IDIO_C_TYPE_ulong
#define idio_isa_libc___ino_t               idio_isa_C_ulong

#define IDIO_TYPE_C_libc___nlink_t          IDIO_TYPE_C_ULONG
#define idio_libc___nlink_t                 idio_C_ulong
#define IDIO_C_TYPE_libc___nlink_t          IDIO_C_TYPE_ulong
#define idio_isa_libc___nlink_t             idio_isa_C_ulong

#define IDIO_TYPE_C_libc___off_t            IDIO_TYPE_C_LONG
#define idio_libc___off_t                   idio_C_long
#define IDIO_C_TYPE_libc___off_t            IDIO_C_TYPE_long
#define idio_isa_libc___off_t               idio_isa_C_long

#define IDIO_TYPE_C_libc___blksize_t        IDIO_TYPE_C_LONG
#define idio_libc___blksize_t               idio_C_long
#define IDIO_C_TYPE_libc___blksize_t        IDIO_C_TYPE_long
#define idio_isa_libc___blksize_t           idio_isa_C_long

#define IDIO_TYPE_C_libc___blkcnt_t         IDIO_TYPE_C_LONG
#define idio_libc___blkcnt_t                idio_C_long
#define IDIO_C_TYPE_libc___blkcnt_t         IDIO_C_TYPE_long
#define idio_isa_libc___blkcnt_t            idio_isa_C_long

#define IDIO_TYPE_C_libc___syscall_slong_t  IDIO_TYPE_C_LONG
#define idio_libc___syscall_slong_t         idio_C_long
#define IDIO_C_TYPE_libc___syscall_slong_t  IDIO_C_TYPE_long
#define idio_isa_libc___syscall_slong_t     idio_isa_C_long

#define IDIO_TYPE_C_libc___fsblkcnt_t       IDIO_TYPE_C_ULONG
#define idio_libc___fsblkcnt_t              idio_C_ulong
#define IDIO_C_TYPE_libc___fsblkcnt_t       IDIO_C_TYPE_ulong
#define idio_isa_libc___fsblkcnt_t          idio_isa_C_ulong

#define IDIO_TYPE_C_libc___fsfilcnt_t       IDIO_TYPE_C_ULONG
#define idio_libc___fsfilcnt_t              idio_C_ulong
#define IDIO_C_TYPE_libc___fsfilcnt_t       IDIO_C_TYPE_ulong
#define idio_isa_libc___fsfilcnt_t          idio_isa_C_ulong

/* /usr/lib/gcc/x86_64-redhat-linux/12/include/stddef.h */
#define IDIO_TYPE_C_libc_size_t             IDIO_TYPE_C_ULONG
#define idio_libc_size_t                    idio_C_ulong
#define IDIO_C_TYPE_libc_size_t             IDIO_C_TYPE_ulong
#define idio_isa_libc_size_t                idio_isa_C_ulong

/* /usr/include/sys/resource.h */
#define IDIO_TYPE_C_libc___priority_which_t IDIO_TYPE_C_uint
#define idio_libc___priority_which_t        idio_C_uint
#define IDIO_C_TYPE_libc___priority_which_t IDIO_C_TYPE_uint
#define idio_isa_libc___priority_which_t    idio_isa_C_uint

/* /usr/include/bits/types.h */
#define IDIO_TYPE_C_libc___id_t             IDIO_TYPE_C_UINT
#define idio_libc___id_t                    idio_C_uint
#define IDIO_C_TYPE_libc___id_t             IDIO_C_TYPE_uint
#define idio_isa_libc___id_t                idio_isa_C_uint

/* /usr/include/sys/types.h */
#define IDIO_TYPE_C_libc_id_t               IDIO_TYPE_C_libc___id_t
#define idio_libc_id_t                      idio_libc___id_t
#define IDIO_C_TYPE_libc_id_t               IDIO_C_TYPE_libc___id_t
#define idio_isa_libc_id_t                  idio_isa_libc___id_t

/* /usr/include/sys/resource.h */
#define IDIO_TYPE_C_libc___rlimit_resource_t IDIO_TYPE_C_uint
#define idio_libc___rlimit_resource_t       idio_C_uint
#define IDIO_C_TYPE_libc___rlimit_resource_t IDIO_C_TYPE_uint
#define idio_isa_libc___rlimit_resource_t   idio_isa_C_uint

/* /usr/include/bits/types.h */
#define IDIO_TYPE_C_libc___rlim_t           IDIO_TYPE_C_ULONG
#define idio_libc___rlim_t                  idio_C_ulong
#define IDIO_C_TYPE_libc___rlim_t           IDIO_C_TYPE_ulong
#define idio_isa_libc___rlim_t              idio_isa_C_ulong

/* /usr/include/bits/resource.h */
#define IDIO_TYPE_C_libc_rlim_t             IDIO_TYPE_C_libc___rlim_t
#define idio_libc_rlim_t                    idio_libc___rlim_t
#define IDIO_C_TYPE_libc_rlim_t             IDIO_C_TYPE_libc___rlim_t
#define idio_isa_libc_rlim_t                idio_isa_libc___rlim_t

/* /usr/include/sys/resource.h */
#define IDIO_TYPE_C_libc___rusage_who_t     IDIO_TYPE_C_int
#define idio_libc___rusage_who_t            idio_C_int
#define IDIO_C_TYPE_libc___rusage_who_t     IDIO_C_TYPE_int
#define idio_isa_libc___rusage_who_t        idio_isa_C_int

/* /usr/include/bits/types.h */
#define IDIO_TYPE_C_libc___suseconds_t      IDIO_TYPE_C_LONG
#define idio_libc___suseconds_t             idio_C_long
#define IDIO_C_TYPE_libc___suseconds_t      IDIO_C_TYPE_long
#define idio_isa_libc___suseconds_t         idio_isa_C_long

#define IDIO_TYPE_C_libc___intmax_t         IDIO_TYPE_C_LONG
#define idio_libc___intmax_t                idio_C_long
#define IDIO_C_TYPE_libc___intmax_t         IDIO_C_TYPE_long
#define idio_isa_libc___intmax_t            idio_isa_C_long

/* /usr/include/stdint.h */
#define IDIO_TYPE_C_libc_intmax_t           IDIO_TYPE_C_libc___intmax_t
#define idio_libc_intmax_t                  idio_libc___intmax_t
#define IDIO_C_TYPE_libc_intmax_t           IDIO_C_TYPE_libc___intmax_t
#define idio_isa_libc_intmax_t              idio_isa_libc___intmax_t

/* /usr/include/bits/types.h */
#define IDIO_TYPE_C_libc___uintmax_t        IDIO_TYPE_C_ULONG
#define idio_libc___uintmax_t               idio_C_ulong
#define IDIO_C_TYPE_libc___uintmax_t        IDIO_C_TYPE_ulong
#define idio_isa_libc___uintmax_t           idio_isa_C_ulong

/* /usr/include/stdint.h */
#define IDIO_TYPE_C_libc_uintmax_t          IDIO_TYPE_C_libc___uintmax_t
#define idio_libc_uintmax_t                 idio_libc___uintmax_t
#define IDIO_C_TYPE_libc_uintmax_t          IDIO_C_TYPE_libc___uintmax_t
#define idio_isa_libc_uintmax_t             idio_isa_libc___uintmax_t

/* /usr/include/bits/types.h */
#define IDIO_TYPE_C_libc___intptr_t         IDIO_TYPE_C_LONG
#define idio_libc___intptr_t                idio_C_long
#define IDIO_C_TYPE_libc___intptr_t         IDIO_C_TYPE_long
#define idio_isa_libc___intptr_t            idio_isa_C_long

/* /usr/include/unistd.h */
#define IDIO_TYPE_C_libc_intptr_t           IDIO_TYPE_C_libc___intptr_t
#define idio_libc_intptr_t                  idio_libc___intptr_t
#define IDIO_C_TYPE_libc_intptr_t           IDIO_C_TYPE_libc___intptr_t
#define idio_isa_libc_intptr_t              idio_isa_libc___intptr_t

/* /usr/include/sys/types.h */
#define IDIO_TYPE_C_libc_mode_t             IDIO_TYPE_C_libc___mode_t
#define idio_libc_mode_t                    idio_libc___mode_t
#define IDIO_C_TYPE_libc_mode_t             IDIO_C_TYPE_libc___mode_t
#define idio_isa_libc_mode_t                idio_isa_libc___mode_t

#define IDIO_TYPE_C_libc_uid_t              IDIO_TYPE_C_libc___uid_t
#define idio_libc_uid_t                     idio_libc___uid_t
#define IDIO_C_TYPE_libc_uid_t              IDIO_C_TYPE_libc___uid_t
#define idio_isa_libc_uid_t                 idio_isa_libc___uid_t

#define IDIO_TYPE_C_libc_gid_t              IDIO_TYPE_C_libc___gid_t
#define idio_libc_gid_t                     idio_libc___gid_t
#define IDIO_C_TYPE_libc_gid_t              IDIO_C_TYPE_libc___gid_t
#define idio_isa_libc_gid_t                 idio_isa_libc___gid_t

#define IDIO_TYPE_C_libc_pid_t              IDIO_TYPE_C_libc___pid_t
#define idio_libc_pid_t                     idio_libc___pid_t
#define IDIO_C_TYPE_libc_pid_t              IDIO_C_TYPE_libc___pid_t
#define idio_isa_libc_pid_t                 idio_isa_libc___pid_t

#define IDIO_TYPE_C_libc_off_t              IDIO_TYPE_C_libc___off_t
#define idio_libc_off_t                     idio_libc___off_t
#define IDIO_C_TYPE_libc_off_t              IDIO_C_TYPE_libc___off_t
#define idio_isa_libc_off_t                 idio_isa_libc___off_t

#define IDIO_TYPE_C_libc_suseconds_t        IDIO_TYPE_C_libc___suseconds_t
#define idio_libc_suseconds_t               idio_libc___suseconds_t
#define IDIO_C_TYPE_libc_suseconds_t        IDIO_C_TYPE_libc___suseconds_t
#define idio_isa_libc_suseconds_t           idio_isa_libc___suseconds_t

/* /usr/include/sys/poll.h */
#define IDIO_TYPE_C_libc_nfds_t             IDIO_TYPE_C_ULONG
#define idio_libc_nfds_t                    idio_C_ulong
#define IDIO_C_TYPE_libc_nfds_t             IDIO_C_TYPE_ulong
#define idio_isa_libc_nfds_t                idio_isa_C_ulong

/* /usr/include/bits/types.h */
#define IDIO_TYPE_C_libc___ssize_t          IDIO_TYPE_C_LONG
#define idio_libc___ssize_t                 idio_C_long
#define IDIO_C_TYPE_libc___ssize_t          IDIO_C_TYPE_long
#define idio_isa_libc___ssize_t             idio_isa_C_long

/* /usr/include/sys/types.h */
#define IDIO_TYPE_C_libc_ssize_t            IDIO_TYPE_C_libc___ssize_t
#define idio_libc_ssize_t                   idio_libc___ssize_t
#define IDIO_C_TYPE_libc_ssize_t            IDIO_C_TYPE_libc___ssize_t
#define idio_isa_libc_ssize_t               idio_isa_libc___ssize_t

#define IDIO_TYPE_C_libc_dev_t              IDIO_TYPE_C_libc___dev_t
#define idio_libc_dev_t                     idio_libc___dev_t
#define IDIO_C_TYPE_libc_dev_t              IDIO_C_TYPE_libc___dev_t
#define idio_isa_libc_dev_t                 idio_isa_libc___dev_t

#define IDIO_TYPE_C_libc_ino_t              IDIO_TYPE_C_libc___ino_t
#define idio_libc_ino_t                     idio_libc___ino_t
#define IDIO_C_TYPE_libc_ino_t              IDIO_C_TYPE_libc___ino_t
#define idio_isa_libc_ino_t                 idio_isa_libc___ino_t

#define IDIO_TYPE_C_libc_nlink_t            IDIO_TYPE_C_libc___nlink_t
#define idio_libc_nlink_t                   idio_libc___nlink_t
#define IDIO_C_TYPE_libc_nlink_t            IDIO_C_TYPE_libc___nlink_t
#define idio_isa_libc_nlink_t               idio_isa_libc___nlink_t

#define IDIO_TYPE_C_libc_blksize_t          IDIO_TYPE_C_libc___blksize_t
#define idio_libc_blksize_t                 idio_libc___blksize_t
#define IDIO_C_TYPE_libc_blksize_t          IDIO_C_TYPE_libc___blksize_t
#define idio_isa_libc_blksize_t             idio_isa_libc___blksize_t

#define IDIO_TYPE_C_libc_blkcnt_t           IDIO_TYPE_C_libc___blkcnt_t
#define idio_libc_blkcnt_t                  idio_libc___blkcnt_t
#define IDIO_C_TYPE_libc_blkcnt_t           IDIO_C_TYPE_libc___blkcnt_t
#define idio_isa_libc_blkcnt_t              idio_isa_libc___blkcnt_t

#define IDIO_TYPE_C_libc_fsblkcnt_t         IDIO_TYPE_C_libc___fsblkcnt_t
#define idio_libc_fsblkcnt_t                idio_libc___fsblkcnt_t
#define IDIO_C_TYPE_libc_fsblkcnt_t         IDIO_C_TYPE_libc___fsblkcnt_t
#define idio_isa_libc_fsblkcnt_t            idio_isa_libc___fsblkcnt_t

#define IDIO_TYPE_C_libc_fsfilcnt_t         IDIO_TYPE_C_libc___fsfilcnt_t
#define idio_libc_fsfilcnt_t                idio_libc___fsfilcnt_t
#define IDIO_C_TYPE_libc_fsfilcnt_t         IDIO_C_TYPE_libc___fsfilcnt_t
#define idio_isa_libc_fsfilcnt_t            idio_isa_libc___fsfilcnt_t

/* /usr/include/bits/termios.h */
#define IDIO_TYPE_C_libc_tcflag_t           IDIO_TYPE_C_UINT
#define idio_libc_tcflag_t                  idio_C_uint
#define IDIO_C_TYPE_libc_tcflag_t           IDIO_C_TYPE_uint
#define idio_isa_libc_tcflag_t              idio_isa_C_uint

#define IDIO_TYPE_C_libc_cc_t               IDIO_TYPE_C_UCHAR
#define idio_libc_cc_t                      idio_C_uchar
#define IDIO_C_TYPE_libc_cc_t               IDIO_C_TYPE_uchar
#define idio_isa_libc_cc_t                  idio_isa_C_uchar

#define IDIO_TYPE_C_libc_speed_t            IDIO_TYPE_C_UINT
#define idio_libc_speed_t                   idio_C_uint
#define IDIO_C_TYPE_libc_speed_t            IDIO_C_TYPE_uint
#define idio_isa_libc_speed_t               idio_isa_C_uint

/* /usr/include/bits/types.h */
#define IDIO_TYPE_C_libc___clock_t          IDIO_TYPE_C_LONG
#define idio_libc___clock_t                 idio_C_long
#define IDIO_C_TYPE_libc___clock_t          IDIO_C_TYPE_long
#define idio_isa_libc___clock_t             idio_isa_C_long

/* /usr/include/bits/types/clock_t.h */
#define IDIO_TYPE_C_libc_clock_t            IDIO_TYPE_C_libc___clock_t
#define idio_libc_clock_t                   idio_libc___clock_t
#define IDIO_C_TYPE_libc_clock_t            IDIO_C_TYPE_libc___clock_t
#define idio_isa_libc_clock_t               idio_isa_libc___clock_t


/* /usr/include/grp.h */
extern IDIO_C_STRUCT_IDENT_DECL (libc_struct_group);
extern IDIO_SYMBOL_DECL (gr_name);
extern IDIO_SYMBOL_DECL (gr_passwd);
extern IDIO_SYMBOL_DECL (gr_gid);
extern IDIO_SYMBOL_DECL (gr_mem);

IDIO idio_libc_struct_group_as_string (struct group *groupp);

/* /usr/include/pwd.h */
extern IDIO_C_STRUCT_IDENT_DECL (libc_struct_passwd);
extern IDIO_SYMBOL_DECL (pw_name);
extern IDIO_SYMBOL_DECL (pw_passwd);
extern IDIO_SYMBOL_DECL (pw_uid);
extern IDIO_SYMBOL_DECL (pw_gid);
extern IDIO_SYMBOL_DECL (pw_gecos);
extern IDIO_SYMBOL_DECL (pw_dir);
extern IDIO_SYMBOL_DECL (pw_shell);

IDIO idio_libc_struct_passwd_as_string (struct passwd *passwdp);

/* /usr/include/sys/poll.h */
extern IDIO_C_STRUCT_IDENT_DECL (libc_struct_pollfd);
extern IDIO_SYMBOL_DECL (fd);
extern IDIO_SYMBOL_DECL (events);
extern IDIO_SYMBOL_DECL (revents);

IDIO idio_libc_struct_pollfd_as_string (struct pollfd *pollfdp);

/* /usr/include/bits/resource.h */
extern IDIO_C_STRUCT_IDENT_DECL (libc_struct_rlimit);
extern IDIO_SYMBOL_DECL (rlim_cur);
extern IDIO_SYMBOL_DECL (rlim_max);

IDIO idio_libc_struct_rlimit_as_string (struct rlimit *rlimitp);

/* /usr/include/bits/types/struct_rusage.h */
extern IDIO_C_STRUCT_IDENT_DECL (libc_struct_rusage);
extern IDIO_SYMBOL_DECL (ru_utime);
extern IDIO_SYMBOL_DECL (ru_stime);

IDIO idio_libc_struct_rusage_as_string (struct rusage *rusagep);

/* /usr/include/bits/sigaction.h */
extern IDIO_C_STRUCT_IDENT_DECL (libc_struct_sigaction);
extern IDIO_SYMBOL_DECL (__sigaction_handler);
extern IDIO_SYMBOL_DECL (sa_mask);
extern IDIO_SYMBOL_DECL (sa_flags);
extern IDIO_SYMBOL_DECL (sa_restorer);

IDIO idio_libc_struct_sigaction_as_string (struct sigaction *sigactionp);

/* /usr/include/bits/struct_stat.h */
extern IDIO_C_STRUCT_IDENT_DECL (libc_struct_stat);
extern IDIO_SYMBOL_DECL (st_dev);
extern IDIO_SYMBOL_DECL (st_ino);
extern IDIO_SYMBOL_DECL (st_nlink);
extern IDIO_SYMBOL_DECL (st_mode);
extern IDIO_SYMBOL_DECL (st_uid);
extern IDIO_SYMBOL_DECL (st_gid);
extern IDIO_SYMBOL_DECL (__pad0);
extern IDIO_SYMBOL_DECL (st_rdev);
extern IDIO_SYMBOL_DECL (st_size);
extern IDIO_SYMBOL_DECL (st_blksize);
extern IDIO_SYMBOL_DECL (st_blocks);
extern IDIO_SYMBOL_DECL (st_atim);
extern IDIO_SYMBOL_DECL (st_mtim);
extern IDIO_SYMBOL_DECL (st_ctim);
extern IDIO_SYMBOL_DECL (__glibc_reserved);

IDIO idio_libc_struct_stat_as_string (struct stat *statp);

/* /usr/include/bits/statvfs.h */
extern IDIO_C_STRUCT_IDENT_DECL (libc_struct_statvfs);
extern IDIO_SYMBOL_DECL (f_bsize);
extern IDIO_SYMBOL_DECL (f_frsize);
extern IDIO_SYMBOL_DECL (f_blocks);
extern IDIO_SYMBOL_DECL (f_bfree);
extern IDIO_SYMBOL_DECL (f_bavail);
extern IDIO_SYMBOL_DECL (f_files);
extern IDIO_SYMBOL_DECL (f_ffree);
extern IDIO_SYMBOL_DECL (f_favail);
extern IDIO_SYMBOL_DECL (f_fsid);
extern IDIO_SYMBOL_DECL (f_flag);
extern IDIO_SYMBOL_DECL (f_namemax);
extern IDIO_SYMBOL_DECL (__f_spare);

IDIO idio_libc_struct_statvfs_as_string (struct statvfs *statvfsp);

/* /usr/include/bits/termios-struct.h */
extern IDIO_C_STRUCT_IDENT_DECL (libc_struct_termios);
extern IDIO_SYMBOL_DECL (c_iflag);
extern IDIO_SYMBOL_DECL (c_oflag);
extern IDIO_SYMBOL_DECL (c_cflag);
extern IDIO_SYMBOL_DECL (c_lflag);
extern IDIO_SYMBOL_DECL (c_line);
extern IDIO_SYMBOL_DECL (c_cc);
extern IDIO_SYMBOL_DECL (c_ispeed);
extern IDIO_SYMBOL_DECL (c_ospeed);

IDIO idio_libc_struct_termios_as_string (struct termios *termiosp);

/* /usr/include/bits/types/struct_timespec.h */
extern IDIO_C_STRUCT_IDENT_DECL (libc_struct_timespec);
extern IDIO_SYMBOL_DECL (tv_sec);
extern IDIO_SYMBOL_DECL (tv_nsec);

IDIO idio_libc_struct_timespec_as_string (struct timespec *timespecp);

/* /usr/include/bits/types/struct_timeval.h */
extern IDIO_C_STRUCT_IDENT_DECL (libc_struct_timeval);
/* tv_sec previously declared */
extern IDIO_SYMBOL_DECL (tv_usec);

IDIO idio_libc_struct_timeval_as_string (struct timeval *timevalp);

/* /usr/include/bits/types/struct_tm.h */
extern IDIO_C_STRUCT_IDENT_DECL (libc_struct_tm);
extern IDIO_SYMBOL_DECL (tm_sec);
extern IDIO_SYMBOL_DECL (tm_min);
extern IDIO_SYMBOL_DECL (tm_hour);
extern IDIO_SYMBOL_DECL (tm_mday);
extern IDIO_SYMBOL_DECL (tm_mon);
extern IDIO_SYMBOL_DECL (tm_year);
extern IDIO_SYMBOL_DECL (tm_wday);
extern IDIO_SYMBOL_DECL (tm_yday);
extern IDIO_SYMBOL_DECL (tm_isdst);
extern IDIO_SYMBOL_DECL (tm_gmtoff);
extern IDIO_SYMBOL_DECL (tm_zone);

IDIO idio_libc_struct_tm_as_string (struct tm *tmp);

/* /usr/include/sys/times.h */
extern IDIO_C_STRUCT_IDENT_DECL (libc_struct_tms);
extern IDIO_SYMBOL_DECL (tms_utime);
extern IDIO_SYMBOL_DECL (tms_stime);
extern IDIO_SYMBOL_DECL (tms_cutime);
extern IDIO_SYMBOL_DECL (tms_cstime);

IDIO idio_libc_struct_tms_as_string (struct tms *tmsp);

/* /usr/include/sys/utsname.h */
extern IDIO_C_STRUCT_IDENT_DECL (libc_struct_utsname);
extern IDIO_SYMBOL_DECL (sysname);
extern IDIO_SYMBOL_DECL (nodename);
extern IDIO_SYMBOL_DECL (release);
/* version is defined by Idio */
extern IDIO_SYMBOL_DECL (machine);
extern IDIO_SYMBOL_DECL (domainname);

IDIO idio_libc_struct_utsname_as_string (struct utsname *utsnamep);

void idio_libc_api_add_primitives ();

void idio_init_libc_api ();

#endif /* LIBC_API_H */
