#! /bin/bash

# Copyright (c) 2015 Run Scripts Limited
#
# Licensed under the Apache License, Version 2.0 (the "License"); you
# may not use this file except in compliance with the License.  You
# may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

# 
# auto-exit -- die deterministically
#

usage () 
{
    (
	echo "usage: $0 [options]" 
	echo "where options are:" 
	echo "	-e STATUS	exit with STATUS" 
	echo "	-k SIGNAL	kill self with SIGNAL" 
    ) >&2
}

opt_exit=0
opt_kill=

while getopts "e:k:" opt ; do
    case "${opt}" in
    e)
	opt_exit=${OPTARG}
	;;
    k)
	opt_kill=${OPTARG}
	;;
    *)
	usage
	exit 1
	;;
    esac
done

if [[ ${opt_kill} ]] ; then
    kill -${opt_kill} $$
fi

exit ${opt_exit}
