
/*
 * libc-api.c
 *
 *
 * This file was generated by c-api-gen on a Linux 5.10.14-200.fc33.x86_64 x86_64 system
 *
 * It has subsequently been reworked into a normal form (__pid_t to pid_t, etc.).
 */

#include "idio.h"


/*
	/usr/include/sys/utsname.h

	struct utsname
	{
	  char[]               sysname;
	  char[]               nodename;
	  char[]               release;
	  char[]               version;
	  char[]               machine;
	  char[]               domainname;	Linux
	};
*/

IDIO_C_STRUCT_IDENT_DECL(libc_struct_utsname);
IDIO_SYMBOL_DECL (sysname);
IDIO_SYMBOL_DECL (nodename);
IDIO_SYMBOL_DECL (release);
IDIO_SYMBOL_DECL (version);
IDIO_SYMBOL_DECL (machine);

IDIO_DEFINE_PRIMITIVE2_DS ("struct-utsname-ref", libc_struct_utsname_ref, (IDIO utsname, IDIO member), "utsname member", "\
in C, utsname->member			\n\
					\n\
:param utsname: C struct utsname	\n\
:type utsname: C/pointer		\n\
:param member: C struct member		\n\
:type member: symbol			\n\
:return: utsname->member		\n\
:rtype:	varies on member		\n\
")
{
    IDIO_ASSERT (utsname);
    IDIO_ASSERT (member);

    /*
     * Test Case: libc-errors/struct-utsname-ref-bad-pointer-type.idio
     *
     * struct-utsname-ref #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (pointer, utsname);
    if (idio_CSI_libc_struct_utsname != IDIO_C_TYPE_POINTER_PTYPE (utsname)) {
	/*
	 * Test Case: libc-errors/struct-rusage-ref-invalid-pointer-type.idio
	 *
	 * struct-rusage-ref libc/NULL #t
	 */
	idio_error_param_value ("utsname", "should be a struct utsname", IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    /*
     * Test Case: libc-errors/struct-utsname-ref-bad-member-type.idio
     *
     * struct-utsname-ref (libc/uname) #t
     */
    IDIO_USER_TYPE_ASSERT (symbol, member);

    struct utsname *utsnamep = IDIO_C_TYPE_POINTER_P (utsname);
    if (idio_S_sysname == member) {
	return idio_string_C (utsnamep->sysname);
    } else if (idio_S_nodename == member) {
	return idio_string_C (utsnamep->nodename);
    } else if (idio_S_release == member) {
	return idio_string_C (utsnamep->release);
    } else if (idio_S_version == member) {
	return idio_string_C (utsnamep->version);
    } else if (idio_S_machine == member) {
	return idio_string_C (utsnamep->machine);
    } else {
	/*
	 * Test Case: libc-errors/struct-utsname-ref-invalid-member.idio
	 *
	 * struct-utsname-ref (libc/uname) 'not-likely
	 */
        idio_error_param_value ("member", "should be a struct utsname member", IDIO_C_FUNC_LOCATION());

        return idio_S_notreached;
    }

    return idio_S_notreached;
}

/*
	/usr/include/sys/times.h

	struct tms
	{
	  clock_t              tms_utime;
	  clock_t              tms_stime;
	  clock_t              tms_cutime;
	  clock_t              tms_cstime;
	};
*/

IDIO_C_STRUCT_IDENT_DECL(libc_struct_tms);
IDIO_SYMBOL_DECL (tms_utime);
IDIO_SYMBOL_DECL (tms_stime);
IDIO_SYMBOL_DECL (tms_cutime);
IDIO_SYMBOL_DECL (tms_cstime);

IDIO_DEFINE_PRIMITIVE2_DS ("struct-tms-ref", libc_struct_tms_ref, (IDIO tms, IDIO member), "tms member", "\
in C, tms->member			\n\
					\n\
:param tms: C struct tms		\n\
:type tms: C/pointer			\n\
:param member: C struct member		\n\
:type member: symbol			\n\
:return: tms->member			\n\
:rtype:	varies on member		\n\
")
{
    IDIO_ASSERT (tms);
    IDIO_ASSERT (member);

    /*
     * Test Case: libc-errors/struct-tms-ref-bad-pointer-type.idio
     *
     * struct-tms-ref #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (pointer, tms);
    if (idio_CSI_libc_struct_tms != IDIO_C_TYPE_POINTER_PTYPE (tms)) {
	/*
	 * Test Case: libc-errors/struct-tms-ref-invalid-pointer-type.idio
	 *
	 * struct-tms-ref libc/NULL #t
	 */
	idio_error_param_value ("tms", "should be a struct tms", IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    /*
     * Test Case: libc-errors/struct-tms-ref-bad-member-type.idio
     *
     * struct-tms-ref (pht (libc/times)) #t
     */
    IDIO_USER_TYPE_ASSERT (symbol, member);

    struct tms *tmsp = IDIO_C_TYPE_POINTER_P (tms);
    if (idio_S_tms_utime == member) {
        return idio_libc_clock_t (tmsp->tms_utime);
    } else if (idio_S_tms_stime == member) {
        return idio_libc_clock_t (tmsp->tms_stime);
    } else if (idio_S_tms_cutime == member) {
        return idio_libc_clock_t (tmsp->tms_cutime);
    } else if (idio_S_tms_cstime == member) {
        return idio_libc_clock_t (tmsp->tms_cstime);
    } else {
	/*
	 * Test Case: libc-errors/struct-tms-ref-invalid-member.idio
	 *
	 * struct-tms-ref (pht (libc/times)) 'not-likely
	 */
        idio_error_param_value ("member", "should be a struct tms member", IDIO_C_FUNC_LOCATION());

        return idio_S_notreached;
    }

    return idio_S_notreached;
}

/*
	/usr/include/bits/termios-struct.h

	struct termios
	{
	  tcflag_t             c_iflag;
	  tcflag_t             c_oflag;
	  tcflag_t             c_cflag;
	  tcflag_t             c_lflag;
	  cc_t                 c_line;		Linux
	  cc_t[]               c_cc;
	  speed_t              c_ispeed;	Linux
	  speed_t              c_ospeed;	Linux
	};
*/

IDIO_C_STRUCT_IDENT_DECL(libc_struct_termios);
IDIO_SYMBOL_DECL (c_iflag);
IDIO_SYMBOL_DECL (c_oflag);
IDIO_SYMBOL_DECL (c_cflag);
IDIO_SYMBOL_DECL (c_lflag);
IDIO_SYMBOL_DECL (c_line);
IDIO_SYMBOL_DECL (c_cc);
IDIO_SYMBOL_DECL (c_ispeed);
IDIO_SYMBOL_DECL (c_ospeed);

IDIO_DEFINE_PRIMITIVE2_DS ("struct-termios-ref", libc_struct_termios_ref, (IDIO termios, IDIO member), "termios member", "\
in C, termios->member			\n\
					\n\
:param termios: C struct termios	\n\
:type termios: C/pointer		\n\
:param member: C struct member		\n\
:type member: symbol			\n\
:return: termios->member		\n\
:rtype:	varies on member		\n\
")
{
    IDIO_ASSERT (termios);
    IDIO_ASSERT (member);

    /*
     * Test Case: libc-errors/struct-termios-ref-bad-pointer-type.idio
     *
     * struct-termios-ref #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (pointer, termios);
    if (idio_CSI_libc_struct_termios != IDIO_C_TYPE_POINTER_PTYPE (termios)) {
	/*
	 * Test Case: libc-errors/struct-termios-ref-invalid-pointer-type.idio
	 *
	 * struct-termios-ref libc/NULL #t
	 */
	idio_error_param_value ("termios", "should be a struct termios", IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    /*
     * Test Case: libc-errors/struct-termios-ref-bad-member-type.idio
     *
     * struct-termios-ref (libc/tcgetattr libc/STDIN_FILENO) #t
     */
    IDIO_USER_TYPE_ASSERT (symbol, member);

    struct termios *termiosp = IDIO_C_TYPE_POINTER_P (termios);
    if (idio_S_c_iflag == member) {
        return idio_libc_tcflag_t (termiosp->c_iflag);
    } else if (idio_S_c_oflag == member) {
        return idio_libc_tcflag_t (termiosp->c_oflag);
    } else if (idio_S_c_cflag == member) {
        return idio_libc_tcflag_t (termiosp->c_cflag);
    } else if (idio_S_c_lflag == member) {
        return idio_libc_tcflag_t (termiosp->c_lflag);
    } else if (idio_S_c_cc == member) {
        /*
         * WARNING:
         * cc_t[] c_cc
         *
         * sizeof (termiosp->c_cc) is probably incorrect
         *
         * check the API
         */
        size_t alen = sizeof (termiosp->c_cc);
        cc_t *rp = (cc_t *) idio_alloc (alen);
        memcpy ((void *) rp, (void *) &termiosp->c_cc, alen);
        return idio_C_pointer_free_me (rp);
    } else {
	/*
	 * Test Case: libc-errors/struct-termios-ref-invalid-member.idio
	 *
	 * struct-termios-ref (libc/tcgetattr libc/STDIN_FILENO) 'not-likely
	 */
        idio_error_param_value ("member", "should be a struct termios member", IDIO_C_FUNC_LOCATION());

        return idio_S_notreached;
    }

    return idio_S_notreached;
}

IDIO_DEFINE_PRIMITIVE3_DS ("struct-termios-set!", libc_struct_termios_set, (IDIO termios, IDIO member, IDIO val), "termios member val", "\
in C, termios->member = val		\n\
					\n\
:param termios: C struct termios	\n\
:type termios: C/pointer		\n\
:param member: C struct member		\n\
:type member: symbol			\n\
:param val: C/type val			\n\
:type val: varies on member		\n\
:return: termios->member		\n\
:rtype:	varies on member		\n\
")
{
    IDIO_ASSERT (termios);
    IDIO_ASSERT (member);
    IDIO_ASSERT (val);

    /*
     * Test Case: libc-errors/termios-set-bad-pointer-type.idio
     *
     * termios-set! #t #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (pointer, termios);
    if (idio_CSI_libc_struct_termios != IDIO_C_TYPE_POINTER_PTYPE (termios)) {
	/*
	 * Test Case: libc-errors/struct-termios-set-invalid-pointer-type.idio
	 *
	 * struct-termios-set! libc/NULL #t #t
	 */
	idio_error_param_value ("termios", "should be a struct termios", IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    /*
     * Test Case: libc-errors/termios-set-bad-member-type.idio
     *
     * termios-set! (libc/tcgetattr libc/STDIN_FILENO) #t #t
     */
    IDIO_USER_TYPE_ASSERT (symbol, member);

    struct termios *termiosp = IDIO_C_TYPE_POINTER_P (termios);
    if (idio_S_c_iflag == member) {
       /*
	* Test Case: not yet: libc-errors/termios-set-c_iflag-bad-value-type.idio
	*
	* termios-set! v 'c_iflag #t
	*/
	IDIO_USER_libc_TYPE_ASSERT (tcflag_t, val);

        termiosp->c_iflag = IDIO_C_TYPE_libc_tcflag_t (val);
        return idio_S_unspec;
    } else if (idio_S_c_oflag == member) {
       /*
	* Test Case: not yet: libc-errors/termios-set-c_oflag-bad-value-type.idio
	*
	* termios-set! v 'c_oflag #t
	*/
	IDIO_USER_libc_TYPE_ASSERT (tcflag_t, val);

        termiosp->c_oflag = IDIO_C_TYPE_libc_tcflag_t (val);
        return idio_S_unspec;
    } else if (idio_S_c_cflag == member) {
       /*
	* Test Case: not yet: libc-errors/termios-set-c_cflag-bad-value-type.idio
	*
	* termios-set! v 'c_cflag #t
	*/
	IDIO_USER_libc_TYPE_ASSERT (tcflag_t, val);

        termiosp->c_cflag = IDIO_C_TYPE_libc_tcflag_t (val);
        return idio_S_unspec;
    } else if (idio_S_c_lflag == member) {
       /*
	* Test Case: not yet: libc-errors/termios-set-c_lflag-bad-value-type.idio
	*
	* termios-set! v 'c_lflag #t
	*/
	IDIO_USER_libc_TYPE_ASSERT (tcflag_t, val);

        termiosp->c_lflag = IDIO_C_TYPE_libc_tcflag_t (val);
        return idio_S_unspec;
    } else if (idio_S_c_cc == member) {
       /*
	* Test Case: not yet: libc-errors/termios-set-c_cc-bad-value-type.idio
	*
	* termios-set! v 'c_cc #t
	*/
	IDIO_USER_C_TYPE_ASSERT (pointer, val);

        /*
         * WARNING:
         * cc_t[] c_cc
         *
         * sizeof (termiosp->c_cc) is probably incorrect
         *
         * check the API
         */
        cc_t *valp = IDIO_C_TYPE_POINTER_P (val);
        size_t alen = sizeof (termiosp->c_cc);
        memcpy ((void *) &termiosp->c_cc, (void *) valp, alen);
        return idio_S_unspec;
    } else {
	/*
	 * Test Case: libc-errors/struct-termios-set-invalid-member.idio
	 *
	 * struct-termios-set! (libc/uname) 'not-likely
	 */
        idio_error_param_value ("member", "should be a struct termios member", IDIO_C_FUNC_LOCATION());

        return idio_S_notreached;
    }

    return idio_S_notreached;
}

/*
	/usr/include/bits/stat.h

	struct stat
	{
	  __dev_t              st_dev;
	  __ino_t              st_ino;
	  __nlink_t            st_nlink;
	  __mode_t             st_mode;
	  __uid_t              st_uid;
	  __gid_t              st_gid;
	  int                  __pad0;			Linux
	  __dev_t              st_rdev;
	  __off_t              st_size;
	  __blksize_t          st_blksize;
	  __blkcnt_t           st_blocks;
	  struct timespec      st_atim;
	  struct timespec      st_mtim;
	  struct timespec      st_ctim;
	  __syscall_slong_t[]  __glibc_reserved;	Linux
	};
*/

IDIO_C_STRUCT_IDENT_DECL(libc_struct_stat);
IDIO_SYMBOL_DECL (st_dev);
IDIO_SYMBOL_DECL (st_ino);
IDIO_SYMBOL_DECL (st_nlink);
IDIO_SYMBOL_DECL (st_mode);
IDIO_SYMBOL_DECL (st_uid);
IDIO_SYMBOL_DECL (st_gid);
IDIO_SYMBOL_DECL (st_rdev);
IDIO_SYMBOL_DECL (st_size);
IDIO_SYMBOL_DECL (st_blksize);
IDIO_SYMBOL_DECL (st_blocks);
IDIO_SYMBOL_DECL (st_atim);
IDIO_SYMBOL_DECL (st_mtim);
IDIO_SYMBOL_DECL (st_ctim);

/* specials */
IDIO_SYMBOL_DECL (st_atime);
IDIO_SYMBOL_DECL (st_mtime);
IDIO_SYMBOL_DECL (st_ctime);

IDIO_DEFINE_PRIMITIVE2_DS ("struct-stat-ref", libc_struct_stat_ref, (IDIO stat, IDIO member), "stat member", "\
in C, stat->member			\n\
					\n\
:param stat: C struct stat	\n\
:type stat: C/pointer		\n\
:param member: C struct member		\n\
:type member: symbol			\n\
:return: stat->member		\n\
:rtype:	varies on member		\n\
")
{
    IDIO_ASSERT (stat);
    IDIO_ASSERT (member);

    /*
     * Test Case: libc-errors/struct-stat-ref-bad-pointer-type.idio
     *
     * struct-stat-ref #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (pointer, stat);
    if (idio_CSI_libc_struct_stat != IDIO_C_TYPE_POINTER_PTYPE (stat)) {
	/*
	 * Test Case: libc-errors/struct-stat-ref-invalid-pointer-type.idio
	 *
	 * struct-stat-ref libc/NULL #t
	 */
	idio_error_param_value ("stat", "should be a struct stat", IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    /*
     * Test Case: libc-errors/struct-stat-ref-bad-member-type.idio
     *
     * struct-stat-ref (libc/stat ".") #t
     */
    IDIO_USER_TYPE_ASSERT (symbol, member);

    struct stat *statp = IDIO_C_TYPE_POINTER_P (stat);
    if (idio_S_st_dev == member) {
        return idio_libc_dev_t (statp->st_dev);
    } else if (idio_S_st_ino == member) {
        return idio_libc_ino_t (statp->st_ino);
    } else if (idio_S_st_nlink == member) {
        return idio_libc_nlink_t (statp->st_nlink);
    } else if (idio_S_st_mode == member) {
        return idio_libc_mode_t (statp->st_mode);
    } else if (idio_S_st_uid == member) {
        return idio_libc_uid_t (statp->st_uid);
    } else if (idio_S_st_gid == member) {
        return idio_libc_gid_t (statp->st_gid);
    } else if (idio_S_st_rdev == member) {
        return idio_libc_dev_t (statp->st_rdev);
    } else if (idio_S_st_size == member) {
        return idio_libc_off_t (statp->st_size);
    } else if (idio_S_st_blksize == member) {
        return idio_libc_blksize_t (statp->st_blksize);
    } else if (idio_S_st_blocks == member) {
        return idio_libc_blkcnt_t (statp->st_blocks);
    } else if (idio_S_st_atim == member) {
        struct timespec *rp = (struct timespec *) idio_alloc (sizeof (struct timespec));
#if defined (__APPLE__) && defined (__MACH__)
        memcpy ((void *) rp, (void *) &statp->st_atimespec, sizeof (struct timespec));
#else
        memcpy ((void *) rp, (void *) &statp->st_atim, sizeof (struct timespec));
#endif
        return idio_C_pointer_type (idio_CSI_libc_struct_timespec, rp);
    } else if (idio_S_st_atime == member) {
#if defined (__APPLE__) && defined (__MACH__)
        return idio_libc_time_t(statp->st_atimespec.tv_sec);
#else
        return idio_libc_time_t(statp->st_atim.tv_sec);
#endif
    } else if (idio_S_st_mtim == member) {
        struct timespec *rp = (struct timespec *) idio_alloc (sizeof (struct timespec));
#if defined (__APPLE__) && defined (__MACH__)
        memcpy ((void *) rp, (void *) &statp->st_mtimespec, sizeof (struct timespec));
#else
        memcpy ((void *) rp, (void *) &statp->st_mtim, sizeof (struct timespec));
#endif
        return idio_C_pointer_type (idio_CSI_libc_struct_timespec, rp);
    } else if (idio_S_st_mtime == member) {
#if defined (__APPLE__) && defined (__MACH__)
        return idio_libc_time_t (statp->st_mtimespec.tv_sec);
#else
        return idio_libc_time_t (statp->st_mtim.tv_sec);
#endif
    } else if (idio_S_st_ctim == member) {
        struct timespec *rp = (struct timespec *) idio_alloc (sizeof (struct timespec));
#if defined (__APPLE__) && defined (__MACH__)
        memcpy ((void *) rp, (void *) &statp->st_ctimespec, sizeof (struct timespec));
#else
        memcpy ((void *) rp, (void *) &statp->st_ctim, sizeof (struct timespec));
#endif
        return idio_C_pointer_type (idio_CSI_libc_struct_timespec, rp);
    } else if (idio_S_st_ctime == member) {
#if defined (__APPLE__) && defined (__MACH__)
        return idio_libc_time_t (statp->st_ctimespec.tv_sec);
#else
        return idio_libc_time_t (statp->st_ctim.tv_sec);
#endif
    } else {
	/*
	 * Test Case: libc-errors/struct-stat-ref-invalid-member.idio
	 *
	 * struct-stat-ref (libc/stat ".") 'not-likely
	 */
        idio_error_param_value ("member", "should be a struct stat member", IDIO_C_FUNC_LOCATION());

        return idio_S_notreached;
    }

    return idio_S_notreached;
}

/*
	/usr/include/bits/types/struct_timespec.h

	struct timespec
	{
	  __time_t             tv_sec;
	  __syscall_slong_t    tv_nsec;		a long?
	};
*/

IDIO_C_STRUCT_IDENT_DECL(libc_struct_timespec);
IDIO_SYMBOL_DECL (tv_sec);
IDIO_SYMBOL_DECL (tv_nsec);

IDIO_DEFINE_PRIMITIVE2_DS ("struct-timespec-ref", libc_struct_timespec_ref, (IDIO timespec, IDIO member), "timespec member", "\
in C, timespec->member			\n\
					\n\
:param timespec: C struct timespec	\n\
:type timespec: C/pointer		\n\
:param member: C struct member		\n\
:type member: symbol			\n\
:return: timespec->member		\n\
:rtype:	varies on member		\n\
")
{
    IDIO_ASSERT (timespec);
    IDIO_ASSERT (member);

    /*
     * Test Case: libc-errors/struct-timespec-ref-bad-pointer-type.idio
     *
     * struct-timespec-ref #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (pointer, timespec);
    if (idio_CSI_libc_struct_timespec != IDIO_C_TYPE_POINTER_PTYPE (timespec)) {
	/*
	 * Test Case: libc-errors/struct-timespec-ref-invalid-pointer-type.idio
	 *
	 * struct-timespec-ref libc/NULL #t
	 */
	idio_error_param_value ("timespec", "should be a struct timespec", IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }


    /*
     * Test Case: libc-errors/struct-timespec-ref-bad-member-type.idio
     *
     * statbuf := libc/stat "."
     * struct-timespec-ref statbuf.st_atim #t
     */
    IDIO_USER_TYPE_ASSERT (symbol, member);

    struct timespec *timespecp = IDIO_C_TYPE_POINTER_P (timespec);
    if (idio_S_tv_sec == member) {
        return idio_libc_time_t (timespecp->tv_sec);
    } else if (idio_S_tv_nsec == member) {
        return idio_C_long (timespecp->tv_nsec);
    } else {
	/*
	 * Test Case: libc-errors/struct-timespec-ref-invalid-member.idio
	 *
	 * statbuf := libc/stat "."
	 * struct-timespec-ref statbuf.st_atim 'not-likely
	 */
        idio_error_param_value ("member", "should be a struct timespec member", IDIO_C_FUNC_LOCATION());

        return idio_S_notreached;
    }

    return idio_S_notreached;
}

IDIO_DEFINE_PRIMITIVE3_DS ("struct-timespec-set!", libc_struct_timespec_set, (IDIO timespec, IDIO member, IDIO val), "timespec member val", "\
in C, timespec->member = val		\n\
					\n\
:param timespec: C struct timespec	\n\
:type timespec: C/pointer		\n\
:param member: C struct member		\n\
:type member: symbol			\n\
:param val: C/type val			\n\
:type val: varies on member		\n\
:return: timespec->member		\n\
:rtype:	varies on member		\n\
")
{
    IDIO_ASSERT (timespec);
    IDIO_ASSERT (member);
    IDIO_ASSERT (val);

    /*
     * Test Case: libc-errors/struct-timespec-set-bad-pointer-type.idio
     *
     * struct-timespec-set! #t #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (pointer, timespec);
    if (idio_CSI_libc_struct_timespec != IDIO_C_TYPE_POINTER_PTYPE (timespec)) {
	/*
	 * Test Case: libc-errors/struct-timespec-set-invalid-pointer-type.idio
	 *
	 * struct-timespec-set! libc/NULL #t #t
	 */
	idio_error_param_value ("timespec", "should be a struct timespec", IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    /*
     * Test Case: libc-errors/struct-timespec-set-bad-member-type.idio
     *
     * statbuf := libc/stat "."
     * struct-timespec-set! statbuf.st_atim #t #t
     */
    IDIO_USER_TYPE_ASSERT (symbol, member);

    struct timespec *timespecp = IDIO_C_TYPE_POINTER_P (timespec);
    if (idio_S_tv_sec == member) {
       /*
	* Test Case: not yet: libc-errors/timespec-set-tv_sec-bad-value-type.idio
	*
	* timespec-set! v 'tv_sec #t
	*/
	IDIO_USER_libc_TYPE_ASSERT (time_t, val);

        timespecp->tv_sec = IDIO_C_TYPE_libc_time_t (val);
        return idio_S_unspec;
    } else if (idio_S_tv_nsec == member) {
       /*
	* Test Case: not yet: libc-errors/timespec-set-tv_nsec-bad-value-type.idio
	*
	* timespec-set! v 'tv_nsec #t
	*/
	IDIO_USER_C_TYPE_ASSERT (long, val);

        timespecp->tv_nsec = IDIO_C_TYPE_long (val);
        return idio_S_unspec;
    } else {
	/*
	 * Test Case: libc-errors/struct-timespec-set-invalid-member.idio
	 *
	 * statbuf := libc/stat "."
	 * struct-timespec-set! statbuf.st_atim 'not-likely
	 */
        idio_error_param_value ("member", "should be a struct timespec member", IDIO_C_FUNC_LOCATION());

        return idio_S_notreached;
    }

    return idio_S_notreached;
}

/*
	/usr/include/bits/resource.h

	struct rlimit
	{
	  rlim_t               rlim_cur;
	  rlim_t               rlim_max;
	};
*/

IDIO_C_STRUCT_IDENT_DECL(libc_struct_rlimit);
IDIO_SYMBOL_DECL (rlim_cur);
IDIO_SYMBOL_DECL (rlim_max);

IDIO_DEFINE_PRIMITIVE2_DS ("struct-rlimit-ref", libc_struct_rlimit_ref, (IDIO rlimit, IDIO member), "rlimit member", "\
in C, rlimit->member			\n\
					\n\
:param rlimit: C struct rlimit	\n\
:type rlimit: C/pointer		\n\
:param member: C struct member		\n\
:type member: symbol			\n\
:return: rlimit->member		\n\
:rtype:	varies on member		\n\
")
{
    IDIO_ASSERT (rlimit);
    IDIO_ASSERT (member);

    /*
     * Test Case: libc-errors/struct-rlimit-ref-bad-pointer-type.idio
     *
     * struct-rlimit-ref #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (pointer, rlimit);
    if (idio_CSI_libc_struct_rlimit != IDIO_C_TYPE_POINTER_PTYPE (rlimit)) {
	/*
	 * Test Case: libc-errors/struct-rlimit-ref-invalid-pointer-type.idio
	 *
	 * struct-rlimit-ref libc/NULL #t
	 */
	idio_error_param_value ("rlimit", "should be a struct rlimit", IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    /*
     * Test Case: libc-errors/struct-rlimit-ref-bad-member-type.idio
     *
     * struct-rlimit-ref (libc/getrlimit libc/RLIMIT_NOFILE) #t
     */
    IDIO_USER_TYPE_ASSERT (symbol, member);

    struct rlimit *rlimitp = IDIO_C_TYPE_POINTER_P (rlimit);
    if (idio_S_rlim_cur == member) {
        return idio_libc_rlim_t (rlimitp->rlim_cur);
    } else if (idio_S_rlim_max == member) {
        return idio_libc_rlim_t (rlimitp->rlim_max);
    } else {
	/*
	 * Test Case: libc-errors/struct-rlimit-ref-invalid-member.idio
	 *
	 * struct-rlimit-ref (libc/getrlimit libc/RLIMIT_NOFILE) 'not-likely
	 */
        idio_error_param_value ("member", "should be a struct rlimit member", IDIO_C_FUNC_LOCATION());

        return idio_S_notreached;
    }

    return idio_S_notreached;
}

IDIO_DEFINE_PRIMITIVE3_DS ("struct-rlimit-set!", libc_struct_rlimit_set, (IDIO rlimit, IDIO member, IDIO val), "rlimit member val", "\
in C, rlimit->member = val		\n\
					\n\
:param rlimit: C struct rlimit	\n\
:type rlimit: C/pointer		\n\
:param member: C struct member		\n\
:type member: symbol			\n\
:param val: C/type val			\n\
:type val: varies on member		\n\
:return: rlimit->member		\n\
:rtype:	varies on member		\n\
")
{
    IDIO_ASSERT (rlimit);
    IDIO_ASSERT (member);
    IDIO_ASSERT (val);

    /*
     * Test Case: libc-errors/struct-rlimit-set-bad-pointer-type.idio
     *
     * struct-rlimit-set! #t #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (pointer, rlimit);
    if (idio_CSI_libc_struct_rlimit != IDIO_C_TYPE_POINTER_PTYPE (rlimit)) {
	/*
	 * Test Case: libc-errors/struct-rlimit-set-invalid-pointer-type.idio
	 *
	 * struct-rlimit-set! libc/NULL #t #t
	 */
	idio_error_param_value ("rlimit", "should be a struct rlimit", IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    /*
     * Test Case: libc-errors/struct-rlimit-set-bad-member-type.idio
     *
     * struct-rlimit-set! (libc/getrlimit libc/RLIMIT_NOFILE) #t #t
     */
    IDIO_USER_TYPE_ASSERT (symbol, member);

    struct rlimit *rlimitp = IDIO_C_TYPE_POINTER_P (rlimit);
    if (idio_S_rlim_cur == member) {
       /*
	* Test Case: libc-errors/rlimit-set-bad-value-type.idio
	*
	* rlimit-set! v 'rlim_cur #t
	*/
	IDIO_USER_libc_TYPE_ASSERT (rlim_t, val);

        rlimitp->rlim_cur = IDIO_C_TYPE_libc_rlim_t (val);
        return idio_S_unspec;
    } else if (idio_S_rlim_max == member) {
       /*
	* Test Case: libc-errors/rlimit-set-bad-value-type.idio
	*
	* rlimit-set! v 'rlim_max #t
	*/
	IDIO_USER_libc_TYPE_ASSERT (rlim_t, val);

        rlimitp->rlim_max = IDIO_C_TYPE_libc_rlim_t (val);
        return idio_S_unspec;
    } else {
	/*
	 * Test Case: libc-errors/struct-rlimit-set-invalid-member.idio
	 *
	 * struct-rlimit-set! (libc/getrlimit libc/RLIMIT_NOFILE) 'not-likely
	 */
        idio_error_param_value ("member", "should be a struct rlimit member", IDIO_C_FUNC_LOCATION());

        return idio_S_notreached;
    }

    return idio_S_notreached;
}

/*
	/usr/include/bits/types/struct_timeval.h

	struct timeval
	{
	  __time_t             tv_sec;
	  __suseconds_t        tv_usec;
	};
*/

IDIO_C_STRUCT_IDENT_DECL(libc_struct_timeval);
/* tv_sec already declared */
IDIO_SYMBOL_DECL (tv_usec);

IDIO_DEFINE_PRIMITIVE2_DS ("struct-timeval-ref", libc_struct_timeval_ref, (IDIO timeval, IDIO member), "timeval member", "\
in C, timeval->member			\n\
					\n\
:param timeval: C struct timeval	\n\
:type timeval: C/pointer		\n\
:param member: C struct member		\n\
:type member: symbol			\n\
:return: timeval->member		\n\
:rtype:	varies on member		\n\
")
{
    IDIO_ASSERT (timeval);
    IDIO_ASSERT (member);

    /*
     * Test Case: libc-errors/struct-timeval-ref-bad-pointer-type.idio
     *
     * struct-timeval-ref #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (pointer, timeval);
    if (idio_CSI_libc_struct_timeval != IDIO_C_TYPE_POINTER_PTYPE (timeval)) {
	/*
	 * Test Case: libc-errors/struct-timeval-ref-invalid-pointer-type.idio
	 *
	 * struct-timeval-ref libc/NULL #t
	 */
	idio_error_param_value ("timeval", "should be a struct timeval", IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    /*
     * Test Case: libc-errors/struct-timeval-ref-bad-member-type.idio
     *
     * struct-timeval-ref (gettimeofday) #t
     */
    IDIO_USER_TYPE_ASSERT (symbol, member);

    struct timeval *timevalp = IDIO_C_TYPE_POINTER_P (timeval);
    if (idio_S_tv_sec == member) {
        return idio_libc_time_t (timevalp->tv_sec);
    } else if (idio_S_tv_usec == member) {
        return idio_libc_suseconds_t (timevalp->tv_usec);
    } else {
	/*
	 * Test Case: libc-errors/struct-timeval-ref-invalid-member.idio
	 *
	 * struct-timeval-ref (gettimeofday) 'not-likely
	 */
        idio_error_param_value ("member", "should be a struct timeval member", IDIO_C_FUNC_LOCATION());

        return idio_S_notreached;
    }

    return idio_S_notreached;
}

IDIO_DEFINE_PRIMITIVE3_DS ("struct-timeval-set!", libc_struct_timeval_set, (IDIO timeval, IDIO member, IDIO val), "timeval member val", "\
in C, timeval->member = val		\n\
					\n\
:param timeval: C struct timeval	\n\
:type timeval: C/pointer		\n\
:param member: C struct member		\n\
:type member: symbol			\n\
:param val: C/type val			\n\
:type val: varies on member		\n\
:return: timeval->member		\n\
:rtype:	varies on member		\n\
")
{
    IDIO_ASSERT (timeval);
    IDIO_ASSERT (member);
    IDIO_ASSERT (val);

    /*
     * Test Case: libc-errors/struct-timeval-set-bad-pointer-type.idio
     *
     * struct-timeval-set! #t #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (pointer, timeval);
    if (idio_CSI_libc_struct_timeval != IDIO_C_TYPE_POINTER_PTYPE (timeval)) {
	/*
	 * Test Case: libc-errors/struct-timeval-set-invalid-pointer-type.idio
	 *
	 * struct-timeval-set! libc/NULL #t #t
	 */
	idio_error_param_value ("timeval", "should be a struct timeval", IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    /*
     * Test Case: libc-errors/struct-timeval-set-bad-member-type.idio
     *
     * struct-timeval-set! v #t #t
     */
    IDIO_USER_TYPE_ASSERT (symbol, member);

    struct timeval *timevalp = IDIO_C_TYPE_POINTER_P (timeval);
    if (idio_S_tv_sec == member) {
       /*
	* Test Case: not yet: libc-errors/timeval-set-tv_sec-bad-value-type.idio
	*
	* timeval-set! v 'tv_sec #t
	*/
	IDIO_USER_libc_TYPE_ASSERT (time_t, val);

        timevalp->tv_sec = IDIO_C_TYPE_libc_time_t (val);
        return idio_S_unspec;
    } else if (idio_S_tv_usec == member) {
       /*
	* Test Case: not yet: libc-errors/timeval-set-tv_usec-bad-value-type.idio
	*
	* timeval-set! v 'tv_usec #t
	*/
	IDIO_USER_libc_TYPE_ASSERT (suseconds_t, val);

        timevalp->tv_usec = IDIO_C_TYPE_libc_suseconds_t (val);
        return idio_S_unspec;
    } else {
	/*
	 * Test Case: libc-errors/struct-timeval-set-invalid-member.idio
	 *
	 * struct-timeval-set! (gettimeofday) 'not-likely
	 */
        idio_error_param_value ("member", "should be a struct timeval member", IDIO_C_FUNC_LOCATION());

        return idio_S_notreached;
    }

    return idio_S_notreached;
}

/*
	/usr/include/bits/types/struct_rusage.h

	struct rusage
	{
	  struct timeval       ru_utime;
	  struct timeval       ru_stime;
	  union {}             -anon-;
	  union {}             -anon-;
	  union {}             -anon-;
	  union {}             -anon-;
	  union {}             -anon-;
	  union {}             -anon-;
	  union {}             -anon-;
	  union {}             -anon-;
	  union {}             -anon-;
	  union {}             -anon-;
	  union {}             -anon-;
	  union {}             -anon-;
	  union {}             -anon-;
	  union {}             -anon-;
	};
*/

IDIO_C_STRUCT_IDENT_DECL(libc_struct_rusage);
IDIO_SYMBOL_DECL (ru_utime);
IDIO_SYMBOL_DECL (ru_stime);

IDIO_DEFINE_PRIMITIVE2_DS ("struct-rusage-ref", libc_struct_rusage_ref, (IDIO rusage, IDIO member), "rusage member", "\
in C, rusage->member			\n\
					\n\
:param rusage: C struct rusage	\n\
:type rusage: C/pointer		\n\
:param member: C struct member		\n\
:type member: symbol			\n\
:return: rusage->member		\n\
:rtype:	varies on member		\n\
")
{
    IDIO_ASSERT (rusage);
    IDIO_ASSERT (member);

    /*
     * Test Case: libc-errors/struct-rusage-ref-bad-pointer-type.idio
     *
     * struct-rusage-ref #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (pointer, rusage);
    if (idio_CSI_libc_struct_rusage != IDIO_C_TYPE_POINTER_PTYPE (rusage)) {
	/*
	 * Test Case: libc-errors/struct-rusage-ref-invalid-pointer-type.idio
	 *
	 * rusage-ref libc/NULL #t
	 */
	idio_error_param_value ("rusage", "should be a struct rusage", IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    /*
     * Test Case: libc-errors/struct-rusage-ref-bad-member-type.idio
     *
     * struct-rusage-ref (libc/getrusage libc/RUSAGE_SELF) #t
     */
    IDIO_USER_TYPE_ASSERT (symbol, member);

    struct rusage *rusagep = IDIO_C_TYPE_POINTER_P (rusage);
    if (idio_S_ru_utime == member) {
        struct timeval *rp = (struct timeval *) idio_alloc (sizeof (struct timeval));
        memcpy ((void *) rp, (void *) &rusagep->ru_utime, sizeof (struct timeval));
        return idio_C_pointer_type (idio_CSI_libc_struct_timeval, rp);
    } else if (idio_S_ru_stime == member) {
        struct timeval *rp = (struct timeval *) idio_alloc (sizeof (struct timeval));
        memcpy ((void *) rp, (void *) &rusagep->ru_stime, sizeof (struct timeval));
        return idio_C_pointer_type (idio_CSI_libc_struct_timeval, rp);
    } else {
	/*
	 * Test Case: libc-errors/struct-rusage-ref-invalid-member.idio
	 *
	 * struct-rusage-ref (libc/getrusage libc/RUSAGE_SELF) 'not-likely
	 */
        idio_error_param_value ("member", "should be a struct rusage member", IDIO_C_FUNC_LOCATION());

        return idio_S_notreached;
    }

    return idio_S_notreached;
}

IDIO_DEFINE_PRIMITIVE2_DS ("write", libc_write, (IDIO fd, IDIO str), "fd str", "\
in C, write (fd, str)						\n\
a wrapper to libc write (2)					\n\
								\n\
:param fd: file descriptor					\n\
:type fd: C/int							\n\
:param str: string						\n\
:type str: string						\n\
:return: number of bytes written or raises ^system-error	\n\
:rtype: libc/ssize_t						\n\
")
{
    IDIO_ASSERT (fd);
    IDIO_ASSERT (str);

    /*
     * Test Case: libc-wrap-errors/write-bad-fd-type.idio
     *
     * write #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, fd);
    /*
     * Test Case: libc-wrap-errors/write-bad-str-type.idio
     *
     * write (C/integer-> 0) #t
     */
    IDIO_USER_TYPE_ASSERT (string, str);

    int C_fd = IDIO_C_TYPE_int (fd);

    size_t blen = 0;
    char *C_str = idio_string_as_C (str, &blen);

    ssize_t write_r = write (C_fd, C_str, blen);

    if (-1 == write_r) {
	/*
	 * Test Case: libc-wrap-errors/write-bad-fd.idio
	 *
	 * write (C/integer-> -1) "hello\n"
	 */
	idio_error_system_errno ("write", IDIO_LIST2 (fd, str), IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    IDIO_GC_FREE (C_str);

    return idio_libc_ssize_t (write_r);
}

IDIO_DEFINE_PRIMITIVE2_DS ("waitpid", libc_waitpid, (IDIO pid, IDIO options), "pid options", "\
in C, waitpid (pid, statusp, options)				\n\
a wrapper to libc waitpid(2)					\n\
								\n\
:param pid: process ID						\n\
:type pid: libc/pid_t						\n\
:param options: see below					\n\
:type options: C/int						\n\
:return: list of (pid_t, statusp) or raises ^system-error	\n\
:rtype: list							\n\
								\n\
WAIT_ANY is defined as -1 in place of ``pid``.			\n\
								\n\
The following options are defined:				\n\
WNOHANG								\n\
WUNTRACED							\n\
								\n\
``statusp`` is C/pointer to a C ``int *``.  See ``WIFEXITED``,	\n\
``WEXITSTATUS``, ``WIFSIGNALLED``, ``WTERMSIG``, ``WIFSTOPPED``	\n\
for functions to manipulate ``statusp``.			\n\
")
{
    IDIO_ASSERT (pid);
    IDIO_ASSERT (options);

    /*
     * Test Case: libc-wrap-errors/waitpid-bad-pid-type.idio
     *
     * waitpid #t #t
     */
    IDIO_USER_libc_TYPE_ASSERT (pid_t, pid);
    pid_t C_pid = IDIO_C_TYPE_libc_pid_t (pid);

    /*
     * Test Case: libc-wrap-errors/waitpid-bad-options-type.idio
     *
     * waitpid (C/integer-> 0 libc/pid_t) #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, options);
    int C_options = IDIO_C_TYPE_int (options);

    int *statusp = idio_alloc (sizeof (int));
    IDIO istatus = idio_C_pointer_free_me (statusp);

    pid_t waitpid_r = waitpid (C_pid, statusp, C_options);

    if (-1 == waitpid_r) {
	if (ECHILD == errno) {
	    return IDIO_LIST2 (idio_libc_pid_t (0), idio_S_nil);
	}

	/*
	 * Test Case: libc-wrap-errors/waitpid-bad-options.idio
	 *
	 * waitpid (C/integer-> 0 libc/pid_t) (C/integer-> -1)
	 */
	idio_error_system_errno ("waitpid", IDIO_LIST2 (pid, options), IDIO_C_FUNC_LOCATION ());
    }

    return IDIO_LIST2 (idio_libc_pid_t (waitpid_r), istatus);
}

IDIO_DEFINE_PRIMITIVE1_DS ("unlink", libc_unlink, (IDIO pathname), "pathname", "\
in C, unlink (pathname)				\n\
a wrapper to libc unlink(2)			\n\
						\n\
:param pathname: filename to unlink		\n\
:type pathname: string				\n\
:return: 0 or raises ^system-error		\n\
:rtype: C/int					\n\
")
{
    IDIO_ASSERT (pathname);

    /*
     * Test Case: libc-wrap-errors/unlink-bad-type.idio
     *
     * unlink #t
     */
    IDIO_USER_TYPE_ASSERT (string, pathname);
    size_t size = 0;
    char *C_pathname = idio_string_as_C (pathname, &size);
    size_t C_size = strlen (C_pathname);
    if (C_size != size) {
	/*
	 * Test Case: libc-wrap-errors/access-bad-format.idio
	 *
	 * unlink (join-string (make-string 1 #U+0) '("hello" "world"))
	 */
	IDIO_GC_FREE (C_pathname);

	idio_libc_format_error ("unlink: pathname contains an ASCII NUL", pathname, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    int unlink_r = unlink (C_pathname);

    IDIO_GC_FREE (C_pathname);

    if (-1 == unlink_r) {
	/*
	 * Test Case: libc-wrap-errors/unlink-non-existent.idio
	 *
	 * fd+name := mkstemp "XXXXXX"
	 * close (ph fd+name)
	 * delete-file (pht fd+name)
	 * unlink (pht fd+name)
	 */
	idio_error_system_errno ("unlink", pathname, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_int (unlink_r);
}

IDIO_DEFINE_PRIMITIVE0_DS ("uname", libc_uname, (void), "", "\
in C, uname (utsnamep)						\n\
a wrapper to libc uname(3)					\n\
								\n\
:return: struct-utsname or raises ^system-error			\n\
:rtype: C/pointer						\n\
								\n\
Not strictly useful at the moment.  You might want to use	\n\
``libc/idio-uname`` such as:					\n\
								\n\
libc/idio-uname.nodename					\n\
								\n\
instead.							\n\
")
{
    struct utsname *utsnamep = idio_alloc (sizeof (struct utsname));

    if (uname (utsnamep) == -1) {
	/*
	 * Test Case: ??
	 *
	 * EFAULT buf is not valid.
	 */
	idio_error_system_errno ("uname", idio_S_nil, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_pointer_type (idio_CSI_libc_struct_utsname, utsnamep);
}

IDIO_DEFINE_PRIMITIVE0_DS ("times", libc_times, (void), "", "\
in C: times ()							\n\
a wrapper to libc times(3)					\n\
								\n\
:return: (clock_t, struct-tms) or raises ^system-error		\n\
:rtype: list							\n\
								\n\
times(3) is complicated because we need to return the struct tms\n\
that the user would have passed in as a pointer and the clock_t,\n\
elapsed real time, that times(3) returns.			\n\
								\n\
All fields are in clock ticks for which sysconf(_SC_CLK_TCK) is	\n\
available for reference as the exported symbol CLK_TCK.		\n\
")
{
    struct tms* tmsp = idio_alloc (sizeof (struct tms));

    clock_t times_r = times (tmsp);

    /* check for errors */
    if (-1 == times_r) {
	/*
	 * Test Case: ??
	 *
	 * EFAULT tmsp points outside the process's address space.
	 */
        idio_error_system_errno ("times", idio_S_nil, IDIO_C_FUNC_LOCATION ());

        return idio_S_notreached;
    }

    return IDIO_LIST2 (idio_libc_clock_t (times_r), idio_C_pointer_type (idio_CSI_libc_struct_tms, tmsp));
}

IDIO_DEFINE_PRIMITIVE2_DS ("tcsetpgrp", libc_tcsetpgrp, (IDIO fd, IDIO pgrp), "fd pgrp", "\
in C, tcsetpgrp (fd, pgrp)					\n\
a wrapper to libc tcsetpgrp(3)					\n\
								\n\
:param fd: file descriptor					\n\
:type fd: C/int							\n\
:param pgrp: PGID						\n\
:type pgrp: libc/pid_t						\n\
:return: 0 or raises ^system-error				\n\
:rtype: C/int							\n\
")
{
    IDIO_ASSERT (fd);
    IDIO_ASSERT (pgrp);

    /*
     * Test Case: libc-wrap-errors/tcsetpgrp-bad-fd-type.idio
     *
     * tcsetpgrp #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, fd);
    int C_fd = IDIO_C_TYPE_int (fd);

    /*
     * Test Case: libc-wrap-errors/tcsetpgrp-bad-pgrp-type.idio
     *
     * tcsetpgrp (C/integer-> 0) #t
     */
    IDIO_USER_libc_TYPE_ASSERT (pid_t, pgrp);
    pid_t C_pgrp = IDIO_C_TYPE_libc_pid_t (pgrp);

    int tcsetpgrp_r = tcsetpgrp (C_fd, C_pgrp);

    if (-1 == tcsetpgrp_r) {
	/*
	 * Test Case: libc-wrap-errors/tcsetpgrp-bad-fd.idio
	 *
	 * tcsetpgrp (C/integer-> -1) (C/integer-> PID libc/pid_t)
	 */
	idio_error_system_errno ("tcsetpgrp", IDIO_LIST2 (fd, pgrp), IDIO_C_FUNC_LOCATION ());
    }

    return idio_C_int (tcsetpgrp_r);
}

IDIO_DEFINE_PRIMITIVE3_DS ("tcsetattr", libc_tcsetattr, (IDIO fd, IDIO options, IDIO termios), "fd options termios", "\
in C, tcsetattr (fd, options, termios)				\n\
a wrapper to libc tcsetattr(3)					\n\
								\n\
:param fd: file descriptor					\n\
:type fd: C/int							\n\
:param options: see below					\n\
:type options: C/int						\n\
:param termios: struct termios					\n\
:type termios: C/pointer					\n\
:return: 0 or raises ^system-error				\n\
:rtype: C/int							\n\
								\n\
The following options are defined:				\n\
TCSADRAIN							\n\
TCSAFLUSH							\n\
								\n\
See ``tcgetattr`` for obtaining a struct termios.		\n\
")
{
    IDIO_ASSERT (fd);
    IDIO_ASSERT (options);
    IDIO_ASSERT (termios);

    /*
     * Test Case: libc-wrap-errors/tcsetattr-bad-fd-type.idio
     *
     * tcsetattr #t #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, fd);
    int C_fd = IDIO_C_TYPE_int (fd);

    /*
     * Test Case: libc-wrap-errors/tcsetattr-bad-options-type.idio
     *
     * tcsetattr (C/integer-> 0) #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, options);
    int C_options = IDIO_C_TYPE_int (options);

    /*
     * Test Case: libc-wrap-errors/tcsetattr-bad-termios-type.idio
     *
     * tcsetattr (C/integer-> 0) (C/integer-> 0) #t
     */
    IDIO_USER_C_TYPE_ASSERT (pointer, termios);
    struct termios *C_termiosp = IDIO_C_TYPE_POINTER_P (termios);

    int tcsetattr_r = tcsetattr (C_fd, C_options, C_termiosp);

    if (-1 == tcsetattr_r) {
	/*
	 * Test Case: libc-wrap-errors/tcsetattr-bad-fd.idio
	 *
	 * get the attributes of stdin and assign them to fd -1
	 *
	 * tcsetattr (C/integer-> -1) (C/integer-> 0) (tcgetattr (C/integer-> 0))
	 */
	idio_error_system_errno ("tcsetattr", IDIO_LIST3 (fd, options, termios), IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_int (tcsetattr_r);
}

IDIO_DEFINE_PRIMITIVE1_DS ("tcgetpgrp", libc_tcgetpgrp, (IDIO fd), "fd", "\
in C, tcgetpgrp (fd)						\n\
a wrapper to libc tcgetpgrp(3)					\n\
								\n\
:param fd: file descriptor					\n\
:type fd: C/int							\n\
:return: PID or raises ^system-error				\n\
:rtype: libc/pid_t						\n\
")
{
    IDIO_ASSERT (fd);

    /*
     * Test Case: libc-wrap-errors/tcgetpgrp-bad-type.idio
     *
     * tcgetpgrp #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, fd);
    int C_fd = IDIO_C_TYPE_int (fd);

    pid_t pid = tcgetpgrp (C_fd);

    if (-1 == pid) {
	/*
	 * Test Case: libc-wrap-errors/tcgetpgrp-bad-fd.idio
	 *
	 * tcgetpgrp (C/integer-> -1)
	 */
	idio_error_system_errno ("tcgetpgrp", fd, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_libc_pid_t (pid);
}

IDIO_DEFINE_PRIMITIVE1_DS ("tcgetattr", libc_tcgetattr, (IDIO fd), "fd", "\
in C, tcgetattr (fd, termiosp)					\n\
a wrapper to libc tcgetattr(3)					\n\
								\n\
:param fd: file descriptor					\n\
:type fd: C/int							\n\
:return: struct termios or raises ^system-error			\n\
:rtype: C/pointer						\n\
")
{
    IDIO_ASSERT (fd);

    /*
     * Test Case: libc-wrap-errors/tcgetattr-bad-type.idio
     *
     * tcgetattr #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, fd);
    int C_fd = IDIO_C_TYPE_int (fd);

    struct termios *termiosp = idio_alloc (sizeof (struct termios));

    int tcgetattr_r = tcgetattr (C_fd, termiosp);

    if (-1 == tcgetattr_r) {
	/*
	 * Test Case: libc-wrap-errors/tcgetattr-bad-fd.idio
	 *
	 * tcgetattr (C/integer-> -1)
	 */
	idio_error_system_errno ("tcgetattr", fd, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_pointer_type (idio_CSI_libc_struct_termios, termiosp);
}

IDIO_DEFINE_PRIMITIVE1_DS ("strsignal", libc_strsignal, (IDIO sig), "sig", "\
in C, strsignal (sig)						\n\
a wrapper to libc strsignal(3)					\n\
								\n\
:param sig: signal number to describe				\n\
:type sig : C/int						\n\
:return: string describing errnum				\n\
:rtype: string							\n\
								\n\
On some systems (Solaris) #n may be returned for an invalid	\n\
signal number.							\n\
")
{
    IDIO_ASSERT (sig);

    /*
     * Test Case: libc-wrap-errors/strsignal-bad-type.idio
     *
     * strsignal #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, sig);
    int C_sig = IDIO_C_TYPE_int (sig);

    char *strsignal_r = strsignal (C_sig);

    if (NULL == strsignal_r) {
	/*
	 * Code coverage: SunOS
	 *
	 * strsignal -1		; #n
	 */
	return idio_S_nil;
    } else {
	return idio_string_C (strsignal_r);
    }
}

IDIO_DEFINE_PRIMITIVE1_DS ("strerror", libc_strerror, (IDIO errnum), "errnum", "\
in C, strerror (errnum)						\n\
a wrapper to libc strerror(3)					\n\
								\n\
:param errnum: error code to describe				\n\
:type errnum : C/int						\n\
:return: string describing errnum				\n\
:rtype: string							\n\
")
{
    IDIO_ASSERT (errnum);

    /*
     * Test Case: libc-wrap-errors/strerror-bad-type.idio
     *
     * strerror #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, errnum);
    int C_errnum = IDIO_C_TYPE_int (errnum);

    /*
     * Arguably we could make a 0 < errnum < IDIO_LIBC_NERRNO check
     * ourselves, here.
     */

    errno = 0;
    char *strerror_r = strerror (C_errnum);

    if (0 != errno) {
	/*
	 * Test Case: ?? libc-wrap-errors/strerror-bad-errnum.idio
	 *
	 * strerror -1
	 *
	 * XXX this generates "Unknown error -1" which means, I guess, all ints are covered.
	 */
	idio_error_system_errno ("strerror", errnum, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_string_C (strerror_r);
}

IDIO_DEFINE_PRIMITIVE1_DS ("stat", libc_stat, (IDIO pathname), "pathname", "\
in C: stat (pathname)				\n\
a wrapper to libc stat(2)			\n\
						\n\
:param pathname:				\n\
:type pathname: C/pointer			\n\
:return: struct-stat or raises ^system-error	\n\
:rtype: struct instance				\n\
")
{
    IDIO_ASSERT (pathname);

    /*
     * Test Case: libc-wrap-errors/stat-bad-type.idio
     *
     * stat #t
     */
    IDIO_USER_TYPE_ASSERT (string, pathname);

    size_t size = 0;
    char *cpathname = idio_string_as_C (pathname, &size);
    size_t C_size = strlen (cpathname);
    if (C_size != size) {
	/*
	 * Test Case: libc-wrap-errors/access-bad-format.idio
	 *
	 * stat (join-string (make-string 1 #U+0) '("hello" "world"))
	 */
	IDIO_GC_FREE (cpathname);

	idio_libc_format_error ("stat: pathname contains an ASCII NUL", pathname, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    struct stat* statp = idio_alloc (sizeof (struct stat));

    int stat_r = stat (cpathname, statp);

    /* check for errors */
    if (-1 == stat_r) {
	/*
	 * Test Case: libc-wrap-errors/stat-empty-pathname.idio
	 *
	 * stat ""
	 */
	IDIO_GC_FREE (cpathname);

        idio_error_system_errno ("stat", pathname, IDIO_C_FUNC_LOCATION ());

        return idio_S_notreached;
    }

    IDIO_GC_FREE (cpathname);

    /*
     * WARNING: this is probably an incorrect return
     */
    return idio_C_pointer_type (idio_CSI_libc_struct_stat, statp);
}

IDIO_DEFINE_PRIMITIVE1_DS ("sleep", libc_sleep, (IDIO seconds), "seconds", "\
in C, sleep (seconds)						\n\
a wrapper to libc sleep(3)					\n\
								\n\
:param seconds: seconds to sleep				\n\
:type seconds: unsigned fixnum or C/uint			\n\
:return: 0 or the number of seconds left if interrupted		\n\
:rtype: C/uint							\n\
")
{
    IDIO_ASSERT (seconds);

    unsigned int C_seconds = 0;
    if (idio_isa_fixnum (seconds) &&
	IDIO_FIXNUM_VAL (seconds) >= 0) {
	C_seconds = IDIO_FIXNUM_VAL (seconds);
    } else if (idio_isa_C_uint (seconds)) {
	C_seconds = IDIO_C_TYPE_uint (seconds);
    } else {
	/*
	 * Test Case: libc-wrap-errors/sleep-bad-type.idio
	 *
	 * sleep #t
	 */
	idio_error_param_type ("unsigned fixnum|C_uint", seconds, IDIO_C_FUNC_LOCATION ());
    }

    unsigned int sleep_r = sleep (C_seconds);

    return idio_C_uint (sleep_r);
}

IDIO_DEFINE_PRIMITIVE2_DS ("signal", libc_signal, (IDIO sig, IDIO handler), "sig handler", "\
in C, signal (sig, handler)					\n\
a wrapper to libc signal(2)					\n\
								\n\
:param sig: signal						\n\
:type sig: C/int						\n\
:param handler: signal disposition					\n\
:type handler: C/pointer						\n\
:return: previous disposition or raises ^system-error		\n\
:rtype: C/pointer						\n\
								\n\
The following dispositions are defined:				\n\
SIG_IGN								\n\
SIG_DFL								\n\
")
{
    IDIO_ASSERT (sig);
    IDIO_ASSERT (handler);

    /*
     * Test Case: libc-wrap-errors/signal-bad-sig-type.idio
     *
     * signal #t #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, sig);
    /*
     * Test Case: libc-wrap-errors/signal-bad-handler-type.idio
     *
     * signal (C/integer-> 0) #t
     */
    IDIO_USER_C_TYPE_ASSERT (pointer, handler);

    int C_sig = IDIO_C_TYPE_int (sig);
    void (*C_handler) (int) = IDIO_C_TYPE_POINTER_P (handler);

    void (*signal_r) (int) = signal (C_sig, C_handler);

    if (SIG_ERR == signal_r) {
	/*
	 * Test Case: libc-wrap-errors/signal-bad-signal.idio
	 *
	 * signal (C/integer-> -1) SIG_DFL
	 */
	idio_error_system_errno ("signal", IDIO_LIST2 (sig, handler), IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_pointer (signal_r);
}

IDIO_DEFINE_PRIMITIVE2_DS ("setrlimit", libc_setrlimit, (IDIO resource, IDIO rlim), "resource rlim", "\
in C, setrlimit (resource, rlim)				\n\
a wrapper to libc setrlimit (2)					\n\
								\n\
:param resource: resource, see below				\n\
:type resource: C/int						\n\
:param rlim: struct-rlimit					\n\
:type rlim: struct instance					\n\
:return: 0 or raises ^system-error				\n\
:rtype: C/int							\n\
								\n\
The resource names follow C conventions such as ``RLIMIT_AS``	\n\
and ``RLIMIT_NOFILE``.						\n\
								\n\
See ``getrlimit`` to obtain a struct-rlimit.			\n\
")
{
    IDIO_ASSERT (resource);
    IDIO_ASSERT (rlim);

    /*
     * Test Case: setrlimit-bad-resource-type.idio
     *
     * setrlimit #t #t
     *
     * NB Fedora uses an unsigned int enum whereas the
     * IDIO_LIBC_RLIMIT(n) macro defines the names as idio_C_int.
     */
    IDIO_USER_C_TYPE_ASSERT (int, resource);
    int C_resource = IDIO_C_TYPE_int (resource);

    /*
     * Test Case: libc-wrap-errors/setrlimit-bad-rlim-type.idio
     *
     * setrlimit (C/integer-> 0) #t
     */
    IDIO_USER_C_TYPE_ASSERT (pointer, rlim);
    if (idio_CSI_libc_struct_rlimit != IDIO_C_TYPE_POINTER_PTYPE (rlim)) {
	/*
	 * Test Case: libc-errors/setrlimit-invalid-pointer-type.idio
	 *
	 * setrlimit-ref (C/integer-> 0) libc/NULL
	 */
	idio_error_param_value ("rlim", "should be a struct rlimit", IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    struct rlimit *C_rlim = IDIO_C_TYPE_POINTER_P (rlim);

    if (setrlimit (C_resource, C_rlim) == -1) {
	/*
	 * Test Case:  libc-wrap-errors/setrlimit-bad-rlim.idio
	 *
	 * setrlimit (C/integer-> -1) (getrlimit RLIMIT_CPU)
	 */
	idio_error_system_errno ("setrlimit", idio_S_nil, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_S_unspec;
}

IDIO_DEFINE_PRIMITIVE2_DS ("setpgid", libc_setpgid, (IDIO pid, IDIO pgid), "pid pgid", "\
in C, setpgid (pid, pgid)					\n\
a wrapper to libc setpgid(2)					\n\
								\n\
:param pid: process ID						\n\
:type pid: libC/pid_t						\n\
:param pgid: PGID						\n\
:type pgid: libc/pid_t						\n\
:return: 0 or raises ^system-error				\n\
:rtype: C/int							\n\
")
{
    IDIO_ASSERT (pid);
    IDIO_ASSERT (pgid);

    /*
     * Test Case: libc-wrap-errors/setpgid-bad-pid-type.idio
     *
     * setpgid #t #t
     */
    IDIO_USER_libc_TYPE_ASSERT (pid_t, pid);
    pid_t C_pid = IDIO_C_TYPE_libc_pid_t (pid);

    /*
     * Test Case: libc-wrap-errors/setpgid-bad-pgid-type.idio
     *
     * setpgid (C/integer-> PID libc/pid_t) #t
     */
    IDIO_USER_libc_TYPE_ASSERT (pid_t, pgid);
    pid_t C_pgid = IDIO_C_TYPE_libc_pid_t (pgid);

    int setpgid_r = setpgid (C_pid, C_pgid);

    if (-1 == setpgid_r) {
	if (EACCES == errno) {
	    /*
	     * The child has already successfully executed exec() =>
	     * EACCES for us.
	     *
	     * Since the child also ran setpgid() on itself before
	     * calling exec() we should be good.
	     */
	    setpgid_r = 0;
	} else {
	    /*
	     * Test Case: libc-wrap-errors/setpgid-negative-pgid.idio
	     *
	     * setpgid (C/integer-> PID libc/pid_t) (C/integer-> -1 libc/pid_t)
	     */
	    idio_error_system_errno ("setpgid", IDIO_LIST2 (pid, pgid), IDIO_C_FUNC_LOCATION ());
	}
    }

    return idio_C_int (setpgid_r);
}

IDIO_DEFINE_PRIMITIVE1_DS ("getpgid", libc_getpgid, (IDIO pid), "pid", "\
in C: getpgid (pid)		\n\
a wrapper to libc getpgid(2)		\n\
					\n\
:param pid: 				\n\
:type pid: libc/pid_t			\n\
")
{
    IDIO_ASSERT (pid);

   /*
    * Test Case: libc-errors/getpgid-bad-pid-type.idio
    *
    * getpgid #t #t
    */
    IDIO_USER_libc_TYPE_ASSERT (pid_t, pid);
    pid_t C_pid = IDIO_C_TYPE_libc_pid_t (pid);

    pid_t getpgid_r = getpgid (C_pid);

    /* check for errors */
    if (-1 == getpgid_r) {
        idio_error_system_errno ("getpgid", idio_S_nil, IDIO_C_FUNC_LOCATION ());

        return idio_S_notreached;
    }

    return idio_libc_pid_t (getpgid_r);
}

IDIO_DEFINE_PRIMITIVE1_DS ("rmdir", libc_rmdir, (IDIO pathname), "pathname", "\
in C, rmdir (pathname)						\n\
a wrapper to libc rmdir(2)					\n\
								\n\
:param pathname: directory to rmdir				\n\
:type pathname: string						\n\
:return: 0 or raises ^system-error				\n\
:rtype: C/int							\n\
")
{
    IDIO_ASSERT (pathname);

    /*
     * Test Case: libc-wrap-errors/rmdir-bad-type.idio
     *
     * rmdir #t
     */
    IDIO_USER_TYPE_ASSERT (string, pathname);

    size_t size = 0;
    char *C_pathname = idio_string_as_C (pathname, &size);
    size_t C_size = strlen (C_pathname);
    if (C_size != size) {
	/*
	 * Test Case: libc-wrap-errors/rmdir-bad-format.idio
	 *
	 * rmdir (join-string (make-string 1 #U+0) '("hello" "world"))
	 */
	IDIO_GC_FREE (C_pathname);

	idio_libc_format_error ("rmdir: pathname contains an ASCII NUL", pathname, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    int rmdir_r = rmdir (C_pathname);

    IDIO_GC_FREE (C_pathname);

    if (-1 == rmdir_r) {
	/*
	 * Test Case: libc-wrap-errors/rmdir-non-existent.idio
	 *
	 * tmpdir := (make-tmp-dir)
	 * rmdir tmpdir
	 * rmdir tmpdir
	 */
	idio_error_system_errno ("rmdir", pathname, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_int (rmdir_r);
}

IDIO_DEFINE_PRIMITIVE1_DS ("regfree", libc_regfree, (IDIO arg1), "arg1", "\
in C: regfree (arg1)		\n\
a wrapper to libc regfree(3)		\n\
					\n\
:param arg1: 				\n\
:type arg1: C/pointer			\n\
")
{
    IDIO_ASSERT (arg1);

   /*
    * Test Case: libc-errors/regfree-bad-arg1-type.idio
    *
    * regfree #t #t
    */
    IDIO_USER_C_TYPE_ASSERT (pointer, arg1);
    regex_t* carg1 = IDIO_C_TYPE_POINTER_P (arg1);

    regfree (carg1);

    return idio_S_unspec;
}

IDIO_DEFINE_PRIMITIVE5_DS ("regexec", libc_regexec, (IDIO arg1, IDIO arg2, IDIO arg3, IDIO arg4, IDIO arg5), "arg1 arg2 arg3 arg4 arg5", "\
in C: regexec (arg1, arg2, arg3, arg4, arg5)		\n\
a wrapper to libc regexec(3)		\n\
					\n\
:param arg1: 				\n\
:type arg1: C/pointer			\n\
:param arg2: 				\n\
:type arg2: C/pointer			\n\
:param arg3: 				\n\
:type arg3: libc/size_t			\n\
:param arg4: 				\n\
:type arg4: C/pointer			\n\
:param arg5: 				\n\
:type arg5: C/int			\n\
")
{
    IDIO_ASSERT (arg1);
    IDIO_ASSERT (arg2);
    IDIO_ASSERT (arg3);
    IDIO_ASSERT (arg4);
    IDIO_ASSERT (arg5);

   /*
    * Test Case: libc-errors/regexec-bad-arg1-type.idio
    *
    * regexec #t #t
    */
    IDIO_USER_C_TYPE_ASSERT (pointer, arg1);
    regex_t* carg1 = IDIO_C_TYPE_POINTER_P (arg1);

   /*
    * Test Case: libc-errors/regexec-bad-arg2-type.idio
    *
    * regexec #t #t
    */
    IDIO_USER_C_TYPE_ASSERT (pointer, arg2);
    char* carg2 = IDIO_C_TYPE_POINTER_P (arg2);

   /*
    * Test Case: libc-errors/regexec-bad-arg3-type.idio
    *
    * regexec #t #t
    */
    IDIO_USER_libc_TYPE_ASSERT (size_t, arg3);
    size_t carg3 = IDIO_C_TYPE_libc_size_t (arg3);

   /*
    * Test Case: libc-errors/regexec-bad-arg4-type.idio
    *
    * regexec #t #t
    */
    IDIO_USER_C_TYPE_ASSERT (pointer, arg4);
    regmatch_t* carg4 = IDIO_C_TYPE_POINTER_P (arg4);

   /*
    * Test Case: libc-errors/regexec-bad-arg5-type.idio
    *
    * regexec #t #t
    */
    IDIO_USER_C_TYPE_ASSERT (int, arg5);
    int carg5 = IDIO_C_TYPE_int (arg5);

    int regexec_r = regexec (carg1, carg2, carg3, carg4, carg5);

    /* check for errors */
    if (-1 == regexec_r) {
        idio_error_system_errno ("regexec", idio_S_nil, IDIO_C_FUNC_LOCATION ());

        return idio_S_notreached;
    }


    /*
     * WARNING: this is probably an incorrect return
     */
    return idio_C_int (regexec_r);

}

IDIO_DEFINE_PRIMITIVE4_DS ("regerror", libc_regerror, (IDIO arg1, IDIO arg2, IDIO arg3, IDIO arg4), "arg1 arg2 arg3 arg4", "\
in C: regerror (arg1, arg2, arg3, arg4)		\n\
a wrapper to libc regerror(3)		\n\
					\n\
:param arg1: 				\n\
:type arg1: C/int			\n\
:param arg2: 				\n\
:type arg2: C/pointer			\n\
:param arg3: 				\n\
:type arg3: C/pointer			\n\
:param arg4: 				\n\
:type arg4: libc/size_t			\n\
")
{
    IDIO_ASSERT (arg1);
    IDIO_ASSERT (arg2);
    IDIO_ASSERT (arg3);
    IDIO_ASSERT (arg4);

   /*
    * Test Case: libc-errors/regerror-bad-arg1-type.idio
    *
    * regerror #t #t
    */
    IDIO_USER_C_TYPE_ASSERT (int, arg1);
    int carg1 = IDIO_C_TYPE_int (arg1);

   /*
    * Test Case: libc-errors/regerror-bad-arg2-type.idio
    *
    * regerror #t #t
    */
    IDIO_USER_C_TYPE_ASSERT (pointer, arg2);
    regex_t* carg2 = IDIO_C_TYPE_POINTER_P (arg2);

   /*
    * Test Case: libc-errors/regerror-bad-arg3-type.idio
    *
    * regerror #t #t
    */
    IDIO_USER_C_TYPE_ASSERT (pointer, arg3);
    char* carg3 = IDIO_C_TYPE_POINTER_P (arg3);

   /*
    * Test Case: libc-errors/regerror-bad-arg4-type.idio
    *
    * regerror #t #t
    */
    IDIO_USER_libc_TYPE_ASSERT (size_t, arg4);
    size_t carg4 = IDIO_C_TYPE_libc_size_t (arg4);

    size_t regerror_r = regerror (carg1, carg2, carg3, carg4);

    /* check for errors */
    if (-1 == regerror_r) {
        idio_error_system_errno ("regerror", idio_S_nil, IDIO_C_FUNC_LOCATION ());

        return idio_S_notreached;
    }


    /*
     * WARNING: this is probably an incorrect return
     */
    return idio_libc_size_t (regerror_r);

}

IDIO_DEFINE_PRIMITIVE3_DS ("regcomp", libc_regcomp, (IDIO arg1, IDIO arg2, IDIO arg3), "arg1 arg2 arg3", "\
in C: regcomp (arg1, arg2, arg3)		\n\
a wrapper to libc regcomp(3)		\n\
					\n\
:param arg1: 				\n\
:type arg1: C/pointer			\n\
:param arg2: 				\n\
:type arg2: C/pointer			\n\
:param arg3: 				\n\
:type arg3: C/int			\n\
")
{
    IDIO_ASSERT (arg1);
    IDIO_ASSERT (arg2);
    IDIO_ASSERT (arg3);

   /*
    * Test Case: libc-errors/regcomp-bad-arg1-type.idio
    *
    * regcomp #t #t
    */
    IDIO_USER_C_TYPE_ASSERT (pointer, arg1);
    regex_t* carg1 = IDIO_C_TYPE_POINTER_P (arg1);

   /*
    * Test Case: libc-errors/regcomp-bad-arg2-type.idio
    *
    * regcomp #t #t
    */
    IDIO_USER_C_TYPE_ASSERT (pointer, arg2);
    char* carg2 = IDIO_C_TYPE_POINTER_P (arg2);

   /*
    * Test Case: libc-errors/regcomp-bad-arg3-type.idio
    *
    * regcomp #t #t
    */
    IDIO_USER_C_TYPE_ASSERT (int, arg3);
    int carg3 = IDIO_C_TYPE_int (arg3);

    int regcomp_r = regcomp (carg1, carg2, carg3);

    /* check for errors */
    if (-1 == regcomp_r) {
        idio_error_system_errno ("regcomp", idio_S_nil, IDIO_C_FUNC_LOCATION ());

        return idio_S_notreached;
    }


    /*
     * WARNING: this is probably an incorrect return
     */
    return idio_C_int (regcomp_r);

}

/*
 * XXX
 *
 * ssize_t read(int fd, void *buf, size_t count);
 *
 * The nominal limit for count is ssize_t in POSIX (noting that count
 * itself is size_t).
 *
 * Linux suggests it will limit read(2) to 0x7ffff000 (2,147,479,552)
 * bytes on both 32-bit and 64-bit systems.
 *
 * We allow a fixnum (2 bits short of an intptr_t) or a libc/size_t.
 */
IDIO_DEFINE_PRIMITIVE1V_DS ("read", libc_read, (IDIO fd, IDIO args), "fd [count]", "\
in C, read (fd[, count])					\n\
a wrapper to libc read(2)					\n\
								\n\
:param fd: file descriptor					\n\
:type fd: C/int							\n\
:param count: number of bytes to read				\n\
:type count: fixnum or libC/size_t				\n\
:return: string of bytes read or #<eof>				\n\
:rtype: string or #<eof>					\n\
								\n\
count defaults to BUFSIZ					\n\
")
{
    IDIO_ASSERT (fd);

    /*
     * Test Case: libc-wrap-errors/read-bad-type.idio
     *
     * read #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, fd);
    int C_fd = IDIO_C_TYPE_int (fd);

    size_t C_count = BUFSIZ;

    if (idio_S_nil != args) {
	IDIO count = IDIO_PAIR_H (args);

	if (idio_isa_fixnum (count)) {
	    C_count = IDIO_FIXNUM_VAL (count);
	} else if (idio_isa_libc_size_t (count)) {
	    C_count = IDIO_C_TYPE_libc_size_t (count);
	} else {
	    /*
	     * Test Case: libc-wrap-errors/read-bad-count-type.idio
	     *
	     * read (C/integer-> 0) #t
	     */
	    idio_error_param_type ("fixnum|libc/size_t", count, IDIO_C_FUNC_LOCATION ());

	    return idio_S_notreached;
	}
    }

    char *buf = idio_alloc (C_count);

    ssize_t n = read (C_fd, buf, C_count);

    IDIO r;

    if (n) {
	r = idio_string_C_len (buf, n);
    } else {
	r = idio_S_eof;
    }

    IDIO_GC_FREE (buf);

    return r;
}

IDIO_DEFINE_PRIMITIVE0_DS ("pipe", libc_pipe, (void), "", "\
in C, pipe (pipefd)						\n\
a wrapper to libc pipe(2)					\n\
								\n\
:return: pointer to pipe array or raises ^system-error		\n\
:rtype: C/pointer						\n\
								\n\
See ``pipe-reader`` and ``pipe-writer`` for accessors to	\n\
the pipe array.							\n\
")
{
    int *pipefd = idio_alloc (2 * sizeof (int));

    int pipe_r = pipe (pipefd);

    if (-1 == pipe_r) {
	/*
	 * Test Case: ??
	 *
	 * Short of reaching EMFILE/ENFILE there's not much we can do.
	 */
	idio_error_system_errno ("pipe", idio_S_nil, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_pointer_free_me (pipefd);
}

IDIO_DEFINE_PRIMITIVE1_DS ("mkstemp", libc_mkstemp, (IDIO template), "template", "\
in C, mkstemp (template)						\n\
a wrapper to libc mkstemp(3)					\n\
								\n\
:param template: template template				\n\
:type template: string						\n\
:return: a list of (file descriptor and new filename) or raises ^system-error\n\
:rtype: list (C/int, string)					\n\
")
{
    IDIO_ASSERT (template);

    /*
     * Test Case: libc-wrap-errors/mkstemp-bad-type.idio
     *
     * mkstemp #t
     */
    IDIO_USER_TYPE_ASSERT (string, template);

    /*
     * XXX mkstemp() requires a NUL-terminated C string and it will
     * modify the template part.
     */
    size_t size = 0;
    char *C_template = idio_string_as_C (template, &size);
    size_t C_size = strlen (C_template);
    if (C_size != size) {
	/*
	 * Test Case: libc-wrap-errors/mkstemp-bad-format.idio
	 *
	 * mkstemp (join-string (make-string 1 #U+0) '("hello" "world"))
	 */
	IDIO_GC_FREE (C_template);

	idio_libc_format_error ("mkstemp: template contains an ASCII NUL", template, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    int mkstemp_r = mkstemp (C_template);

    if (-1 == mkstemp_r) {
	/*
	 * Test Case: libc-wrap-errors/mkstemp-bad-template.idio
	 *
	 * mkstemp "XXX"
	 */
	IDIO_GC_FREE (C_template);

	idio_error_system_errno ("mkstemp", template, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    /*
     * Yuk!  The semantics of mkstemp are slightly different to
     * mkdtemp, above.  mkdtemp "returns a pointer to the modified
     * template string on success" so we can return a new Idio string.
     *
     * mkstemp, however, "return the file descriptor of the temporary
     * file" with the tacit assumption that the caller can use the
     * modified template to unlink the file.
     *
     * Therefore, we need to return a tuple of the file descriptor and
     * a string of the created file name.
     */
    IDIO filename = idio_string_C (C_template);

    IDIO_GC_FREE (C_template);

    return IDIO_LIST2 (idio_C_int (mkstemp_r), filename);
}

IDIO_DEFINE_PRIMITIVE1_DS ("mkdtemp", libc_mkdtemp, (IDIO template), "template", "\
in C, mkdtemp (template)						\n\
a wrapper to libc mkdtemp(3)					\n\
								\n\
:param template: directory template				\n\
:type template: string						\n\
:return: modified template or raises ^system-error		\n\
:rtype: string							\n\
")
{
    IDIO_ASSERT (template);

    /*
     * Test Case: libc-wrap-errors/mkdtemp-bad-type.idio
     *
     * mkdtemp #t
     */
    IDIO_USER_TYPE_ASSERT (string, template);

    /*
     * XXX mkdtemp() requires a NUL-terminated C string and it will
     * modify the template part.
     */
    size_t size = 0;
    char *C_template = idio_string_as_C (template, &size);
    size_t C_size = strlen (C_template);
    if (C_size != size) {
	/*
	 * Test Case: libc-wrap-errors/mkdtemp-bad-format.idio
	 *
	 * mkdtemp (join-string (make-string 1 #U+0) '("hello" "world"))
	 */
	IDIO_GC_FREE (C_template);

	idio_libc_format_error ("mkdtemp: template contains an ASCII NUL", template, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    char *mkdtemp_r = mkdtemp (C_template);

    if (NULL == mkdtemp_r) {
	/*
	 * Test Case: libc-wrap-errors/mkdtemp-bad-template.idio
	 *
	 * mkdtemp "XXX"
	 */
	IDIO_GC_FREE (C_template);

	idio_error_system_errno ("mkdtemp", template, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    IDIO r = idio_string_C (mkdtemp_r);

    IDIO_GC_FREE (C_template);

    return r;
}

IDIO_DEFINE_PRIMITIVE2_DS ("mkdir", libc_mkdir, (IDIO pathname, IDIO mode), "pathname mode", "\
in C, mkdir (pathname, mode)					\n\
a wrapper to libc mkdir(2)					\n\
								\n\
:param pathname: file name					\n\
:type pathname: string						\n\
:param mode: mkdiribility check(s)				\n\
:type mode: libc/mode_t						\n\
:return: #t or #f						\n\
:rtype: boolean							\n\
")
{
    IDIO_ASSERT (pathname);
    IDIO_ASSERT (mode);

    /*
     * Test Case: libc-wrap-errors/mkdir-bad-pathname-type.idio
     *
     * mkdir #t #t
     */
    IDIO_USER_TYPE_ASSERT (string, pathname);
    size_t size = 0;
    char *C_pathname = idio_string_as_C (pathname, &size);
    size_t C_size = strlen (C_pathname);
    if (C_size != size) {
	/*
	 * Test Case: libc-wrap-errors/mkdir-bad-format.idio
	 *
	 * mkdir (join-string (make-string 1 #U+0) '("hello" "world")) (C/integer-> #o555)
	 */
	IDIO_GC_FREE (C_pathname);

	idio_libc_format_error ("mkdir: pathname contains an ASCII NUL", pathname, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    /*
     * Test Case: libc-wrap-errors/mkdir-bad-mode-type.idio
     *
     * mkdir "." #t
     */
    IDIO_USER_libc_TYPE_ASSERT (mode_t, mode);
    int C_mode = IDIO_C_TYPE_libc_mode_t (mode);

    int mkdir_r = mkdir (C_pathname, C_mode);

    if (-1 == mkdir_r) {
	/*
	 * Test Case: libc-wrap-errors/mkdir-pathname-exists.idio
	 *
	 * fd+name := mkstemp "XXXXXX"
	 * close (ph fd+name)
	 * mkdir (pht fd+name) (C/integer-> #o555 libc/mode_t)
	 *
	 * XXX You'll want an unwind-protect to actually delete the
	 * file!
	 */
	idio_error_system_errno ("mkdir", IDIO_LIST2 (pathname, mode), IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_int (mkdir_r);
}

IDIO_DEFINE_PRIMITIVE2_DS ("kill", libc_kill, (IDIO pid, IDIO sig), "pid sig", "\
in C, kill (pid, sig)						\n\
a wrapper to libc kill(2)					\n\
								\n\
:param pid: process ID						\n\
:type pid: libc/pid_t						\n\
:param fd: signal						\n\
:type fd: C/int							\n\
:return: 0 or raises ^system-error				\n\
:rtype: C/int							\n\
")
{
    IDIO_ASSERT (pid);
    IDIO_ASSERT (sig);

    /*
     * Test Case: libc-wrap-errors/kill-bad-pid-type.idio
     *
     * kill #t #t
     */
    IDIO_USER_libc_TYPE_ASSERT (pid_t, pid);
    pid_t C_pid = IDIO_C_TYPE_libc_pid_t (pid);

    /*
     * Test Case: libc-wrap-errors/kill-bad-sig-type.idio
     *
     * kill (C/integer-> PID libc/pid_t) #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, sig);
    int C_sig = IDIO_C_TYPE_int (sig);

    int kill_r = kill (C_pid, C_sig);

    if (-1 == kill_r) {
	/*
	 * Test Case: libc-wrap-errors/kill-invalid-signal.idio
	 *
	 * ;; technically risky as 98765 could be a valid signal...
	 * kill (C/integer-> PID libc/pid_T) (C/integer-> 98765)
	 */
	idio_error_system_errno ("kill", IDIO_LIST2 (pid, sig), IDIO_C_FUNC_LOCATION ());
    }

    return idio_C_int (kill_r);
}

IDIO_DEFINE_PRIMITIVE1_DS ("isatty", libc_isatty, (IDIO fd), "fd", "\
in C, isatty (fd)						\n\
a wrapper to libc isatty(3)					\n\
								\n\
:param fd: file descriptor					\n\
:type fd: C/int							\n\
:return: 1 or raises ^system-error				\n\
:rtype: C/int							\n\
")
{
    IDIO_ASSERT (fd);

    /*
     * Test Case: libc-wrap-errors/isatty-bad-type.idio
     *
     * isatty #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, fd);

    int C_fd = IDIO_C_TYPE_int (fd);

    int isatty_r = isatty (C_fd);

    if (0 == isatty_r) {
	/*
	 * Test Case: libc-wrap-errors/isatty-not-tty.idio
	 *
	 * fd+name := mkstemp "XXXXXX"
	 * delete-file (pht fd+name)
	 * isatty (ph fd+name)
	 */
	idio_error_system_errno ("isatty", fd, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_int (isatty_r);
}

/*
 * Code coverage:
 *
 * This is primarily for catching when someone else has made us a
 * session leader (hint: rlwrap).
 */
IDIO_DEFINE_PRIMITIVE1_DS ("getsid", libc_getsid, (IDIO pid), "pid", "\
in C, getsid (pid)						\n\
a wrapper to libc getsid(2)					\n\
								\n\
:param pid: getsid pid						\n\
:type pid: libc/pid_t						\n\
:return:							\n\
:rtype: libc/pid_t						\n\
")
{
    IDIO_ASSERT (pid);

    /*
     * Test Case: libc-wrap-errors/getsid-bad-type.idio
     *
     * libc/getsid #t
     */
    IDIO_USER_libc_TYPE_ASSERT (pid_t, pid);
    pid_t C_pid = IDIO_C_TYPE_libc_pid_t (pid);

    pid_t getsid_r = getsid (C_pid);

    if (-1 == getsid_r) {
	/*
	 * Test Case: libc-wrap-errors/getsid-invalid-pid.idio
	 *
	 * int-max := C/->number INT_MAX
	 * getsid (C/integer-> int-max libc/pid_t)
	 *
	 * XXX Probably!
	 *
	 * We're assuming that 1) INT_MAX isn't a valid pid (to
	 * generate the error) and 2) that INT_MAX (a C/int) is less
	 * than or equal to the maximum value in the range of a
	 * libc/pid_t (which is probably a C/int or a C/long but you
	 * never know)
	 */
	idio_error_system_errno ("getsid", pid, IDIO_C_FUNC_LOCATION ());
    }

    return idio_libc_pid_t (getsid_r);
}

IDIO_DEFINE_PRIMITIVE1_DS ("getrusage", libc_getrusage, (IDIO who), "who", "\
in C, getrusage (who, rusagep)					\n\
a wrapper to libc getrusage(2)					\n\
								\n\
:param who: who, see below					\n\
:type who: C/int						\n\
:return: struct-rusage or raises ^system-error			\n\
:rtype: struct-rusage						\n\
								\n\
The parameter `who` refers to RUSAGE_SELF or RUSAGE_CHILDREN	\n\
")
{
    IDIO_ASSERT (who);

    /*
     * Test Case: libc-wrap-errors/getrusage-bad-type.idio
     *
     * getrusage #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, who);
    int C_who = IDIO_C_TYPE_int (who);

    struct rusage *rusagep = (struct rusage *) idio_alloc (sizeof (struct rusage));

    if (-1 == getrusage (C_who, rusagep)) {
	/*
	 * Test Case:  libc-wrap-errors/getrusage-bad-who.idio
	 *
	 * On Linux:
	 *
	 * #define RUSAGE_SELF     0
	 * #define RUSAGE_CHILDREN (-1)
	 * #define RUSAGE_BOTH     (-2)
	 * #define RUSAGE_THREAD   1
	 *
	 * Is that positive/negative, a bit-mask?  15 seems to provoke
	 * EINVAL...
	 *
	 * getrusage (C/integer-> 15)
	 */

	IDIO_GC_FREE (rusagep);

	idio_error_system_errno ("getrusage", who, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_pointer_type (idio_CSI_libc_struct_rusage, rusagep);
}

IDIO_DEFINE_PRIMITIVE1_DS ("getrlimit", libc_getrlimit, (IDIO resource), "resource", "\
in C, getrlimit (resource)					\n\
a wrapper to libc getrlimit (2)					\n\
								\n\
:param resource: resource, see below				\n\
:type resource: C/int						\n\
:return: struct-rlimit or raises ^system-error			\n\
:rtype: struct instance						\n\
								\n\
The resource names follow C conventions such as ``RLIMIT_AS``	\n\
and ``RLIMIT_NOFILE``.						\n\
")
{
    IDIO_ASSERT (resource);

    /*
     * Test Case: libc-wrap-errors/getrlimit-bad-resource-type.idio
     *
     * getrlimit #t
     *
     * NB Fedora uses an unsigned int enum whereas the
     * IDIO_LIBC_RLIMIT(n) macro defines the names as idio_C_int.
     */
    IDIO_USER_C_TYPE_ASSERT (int, resource);
    int C_resource = IDIO_C_TYPE_int (resource);

    struct rlimit *rlimp = idio_alloc (sizeof (struct rlimit));

    if (getrlimit (C_resource, rlimp) == -1) {
	/*
	 * Test Case:  libc-wrap-errors/getrlimit-bad-rlim.idio
	 *
	 * getrlimit (C/integer-> -1)
	 */
	idio_error_system_errno ("getrlimit", idio_S_nil, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_pointer_type (idio_CSI_libc_struct_rlimit, rlimp);
}

IDIO_DEFINE_PRIMITIVE0_DS ("getpid", libc_getpid, (void), "", "\
in C, getpid ()							\n\
a wrapper to libc getpid(2)					\n\
								\n\
:return: PID or raises ^system-error				\n\
:rtype: libc/pid_t						\n\
")
{
    /*
     * XXX getpid(2) is always successful.
     */
    return idio_libc_pid_t (getpid ());
}

IDIO_DEFINE_PRIMITIVE0_DS ("getpgrp", libc_getpgrp, (void), "", "\
in C, getpgrp ()						\n\
a wrapper to libc getpgrp(2)					\n\
								\n\
:return: PGID or raises ^system-error				\n\
:rtype: libc/pid_t						\n\
")
{
    pid_t pid = getpgrp ();

    if (-1 == pid) {
	/*
	 * Test Case: ??
	 *
	 * Not sure this POSIX.1 variant getpgrp(2) can fail...here's
	 * hoping!
	 */
	idio_error_system_errno ("getpgrp", idio_S_nil, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_libc_pid_t (pid);
}

IDIO_DEFINE_PRIMITIVE0_DS ("getcwd", libc_getcwd, (void), "", "\
in C, getcwd (buf, size)					\n\
a wrapper to libc getcwd(3)					\n\
								\n\
:return: CWD or raises ^system-error				\n\
:rtype: string							\n\
")
{
    /*
     * getcwd(3) and its arguments
     *
     * A sensible {size}?
     *
     * PATH_MAX varies: POSIX is 256, CentOS 7 is 4096
     *
     * The Linux man page for realpath(3) suggests that calling
     * pathconf(3) for _PC_PATH_MAX doesn't improve matters a whole
     * bunch as it can return a value that is infeasible to allocate
     * in memory.
     *
     * Some systems (OS X, FreeBSD) suggest getcwd(3) should accept
     * MAXPATHLEN (which is #define'd as PATH_MAX in <sys/param.h>).
     *
     * A NULL {buf}?
     *
     * Some systems (older OS X, FreeBSD) do not support a zero {size}
     * parameter.  If passed a NULL {buf}, those systems seem to
     * allocate as much memory as is required to contain the result,
     * regardless of {size}.
     *
     * On systems that do support a zero {size} parameter then they
     * will limit themselves to allocating a maximum of {size} bytes
     * if passed a NULL {buf} and a non-zero {size}.
     *
     * Given that we can't set {size} to zero on some systems then
     * always set {size} to PATH_MAX which should be be enough.
     *
     * Bah! Until Fedora 33/gcc 10.2.1 which is complaining:
     *
     *  warning: argument 1 is null but the corresponding size argument 2 value is 4096
     *
     * It also helpfully reports that:
     *
     *  /usr/include/unistd.h:520:14: note: in a call to function ‘getcwd’ declared with attribute ‘write_only (1, 2)’
     *
     * See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96832
     *
     * If getcwd(3) returns a value that consumes all of PATH_MAX (or
     * more) then we're doomed to hit other problems in the near
     * future anyway as other parts of the system try to use the
     * result.
     */
    char *cwd = getcwd (NULL, PATH_MAX);

    if (NULL == cwd) {
	/*
	 * Test Case: libc-wrap-errors/getcwd-no-access.idio
	 *
	 * tmpdir := (make-tmp-dir)
	 * chdir tmpdir
	 * chmod -rx tmpdir
	 * (getcwd)
	 */
	idio_error_system_errno ("getcwd", idio_S_nil, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    IDIO r = idio_string_C (cwd);
    /*
     * XXX getcwd() used system allocator
     */
    free (cwd);

    return r;
}

IDIO_DEFINE_PRIMITIVE0_DS ("fork", libc_fork, (void), "", "\
in C, fork ()							\n\
a wrapper to libc fork(2)					\n\
								\n\
:return: 0 or PID						\n\
:rtype: libc/pid_t						\n\
")
{
    pid_t C_pid = fork ();

    if (-1 == C_pid) {
	/*
	 * Test Case: ??
	 *
	 * How do you make fork(2) fail?
	 */
	idio_error_system_errno ("fork", idio_S_nil, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_libc_pid_t (C_pid);
}

IDIO_DEFINE_PRIMITIVE2V_DS ("fcntl", libc_fcntl, (IDIO fd, IDIO cmd, IDIO args), "fd cmd [args]", "\
in C, fcntl (fd, cmd[, args])					\n\
a wrapper to libc fcntl(2)					\n\
								\n\
:param fd: file descriptor					\n\
:type fd: C/int or fixnum					\n\
:param cmd: fcntl command					\n\
:type cmd: C/int						\n\
:param args: fcntl command args					\n\
:type args: list						\n\
:return: appropriate value or raises ^system-error		\n\
:rtype: C/int							\n\
								\n\
Supported commands include:					\n\
F_DUPFD								\n\
F_DUPFD_CLOEXEC (if supported)					\n\
F_GETFL								\n\
F_SETFL								\n\
"
)
{
    IDIO_ASSERT (fd);
    IDIO_ASSERT (cmd);
    IDIO_ASSERT (args);

    int C_fd = 0;
    if (idio_isa_fixnum (fd)) {
	C_fd = IDIO_FIXNUM_VAL (fd);
    } else if (idio_isa_C_int (fd)) {
	C_fd = IDIO_C_TYPE_int (fd);
    } else {
	/*
	 * Test Case: libc-wrap-errors/fcntl-bad-fd-type.idio
	 *
	 * fcntl #t F_DUPFD
	 */
	idio_error_param_type ("fixnum|C/int fd", fd, IDIO_C_FUNC_LOCATION ());
    }

    int C_cmd = 0;
    if (idio_isa_C_int (cmd)) {
	C_cmd = IDIO_C_TYPE_int (cmd);
    } else {
	/*
	 * Test Case: libc-wrap-errors/fcntl-bad-cmd-type.idio
	 *
	 * fcntl 0 1
	 */
	idio_error_param_type ("C/int cmd", cmd, IDIO_C_FUNC_LOCATION ());
    }

    IDIO iarg = idio_list_head (args);

    int fcntl_r;

    switch (C_cmd) {
    case F_DUPFD:
	{
	    /*
	     * CentOS 6 i386 fcntl(2) says it wants long but accepts
	     * int
	     */
	    int arg;
	    if (idio_isa_fixnum (iarg)) {
		arg = IDIO_FIXNUM_VAL (iarg);
	    } else if (idio_isa_C_int (iarg)) {
		arg = IDIO_C_TYPE_int (iarg);
	    } else {
		/*
		 * Test Case: libc-wrap-errors/fcntl-F_DUPFD-bad-arg-type.idio
		 *
		 * fcntl 0 F_DUPFD #t
		 */
		idio_error_param_type ("fixnum|C/int", iarg, IDIO_C_FUNC_LOCATION ());

		return idio_S_notreached;
	    }
	    fcntl_r = fcntl (C_fd, C_cmd, arg);
	}
	break;
#if defined (F_DUPFD_CLOEXEC)
    case F_DUPFD_CLOEXEC:
	{
	    /*
	     * CentOS 6 i386 fcntl(2) says it wants long but accepts
	     * int
	     */
	    int arg;
	    if (idio_isa_fixnum (iarg)) {
		arg = IDIO_FIXNUM_VAL (iarg);
	    } else if (idio_isa_C_int (iarg)) {
		arg = IDIO_C_TYPE_int (iarg);
	    } else {
		/*
		 * Test Case: libc-wrap-errors/fcntl-F_DUPFD_CLOEXEC-bad-arg-type.idio
		 *
		 * fcntl 0 F_DUPFD_CLOEXEC #t
		 */
		idio_error_param_type ("fixnum|C/int", iarg, IDIO_C_FUNC_LOCATION ());

		return idio_S_notreached;
	    }
	    fcntl_r = fcntl (C_fd, C_cmd, arg);
	}
	break;
#endif
    case F_GETFD:
	{
	    fcntl_r = fcntl (C_fd, C_cmd);
	}
	break;
    case F_SETFD:
	{
	    int arg;
	    if (idio_isa_C_int (iarg)) {
		arg = IDIO_C_TYPE_int (iarg);
	    } else {
		/*
		 * Test Case: libc-wrap-errors/fcntl-F_SETFD-bad-arg-type.idio
		 *
		 * fcntl 0 F_SETFD #t
		 */
		idio_error_param_type ("C/int", iarg, IDIO_C_FUNC_LOCATION ());

		return idio_S_notreached;
	    }
	    fcntl_r = fcntl (C_fd, C_cmd, arg);
	}
	break;
    case F_GETFL:
	{
	    fcntl_r = fcntl (C_fd, C_cmd);
	}
	break;
    case F_SETFL:
	{
	    int arg;
	    if (idio_isa_C_int (iarg)) {
		arg = IDIO_C_TYPE_int (iarg);
	    } else {
		/*
		 * Test Case: libc-wrap-errors/fcntl-F_SETFL-bad-arg-type.idio
		 *
		 * fcntl 0 F_SETFL #t
		 */
		idio_error_param_type ("C/int", iarg, IDIO_C_FUNC_LOCATION ());

		return idio_S_notreached;
	    }
	    fcntl_r = fcntl (C_fd, C_cmd, arg);
	}
	break;
    default:
	/*
	 * Test Case: libc-wrap-errors/fcntl-unknown-cmd.idio
	 *
	 * fcntl 0 (C/integer-> 98765)
	 */
	idio_error_param_value ("fcntl", "unexpected cmd", IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    if (-1 == fcntl_r) {
	/*
	 * Test Case: libc-wrap-errors/fcntl-F_DUPFD-bad-fd.idio
	 *
	 * fd+name := mkstemp "XXXXXX"
	 * close (ph fd+name)
	 * delete-file (pht fd+name)
	 * fcntl (ph fd+name) F_DUPFD 0
	 */
	idio_error_system_errno ("fcntl", IDIO_LIST3 (fd, cmd, args), IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_int (fcntl_r);
}

IDIO_DEFINE_PRIMITIVE2_DS ("dup2", libc_dup2, (IDIO ioldfd, IDIO inewfd), "oldfd newfd", "\
in C, dup2 (oldfd, newfd)					\n\
a wrapper to libc dup2(2)					\n\
								\n\
:param oldfd: file descriptor					\n\
:type oldfd: C/int or fixnum					\n\
:param newfd: file descriptor					\n\
:type newfd: C/int or fixnum					\n\
:return: new fd or raises ^system-error				\n\
:rtype: C/int							\n\
")
{
    IDIO_ASSERT (ioldfd);
    IDIO_ASSERT (inewfd);

    int C_oldfd = -1;
    if (idio_isa_fixnum (ioldfd)) {
	C_oldfd = IDIO_FIXNUM_VAL (ioldfd);
    } else if (idio_isa_C_int (ioldfd)) {
	C_oldfd = IDIO_C_TYPE_int (ioldfd);
    } else {
	/*
	 * Test Case: libc-wrap-errors/dup2-bad-type.idio
	 *
	 * dup2 #t 99
	 */
	idio_error_param_type ("fixnum|C/int oldfd", ioldfd, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    int C_newfd = -1;
    if (idio_isa_fixnum (inewfd)) {
	C_newfd = IDIO_FIXNUM_VAL (inewfd);
    } else if (idio_isa_C_int (inewfd)) {
	C_newfd = IDIO_C_TYPE_int (inewfd);
    } else {
	/*
	 * Test Case: libc-wrap-errors/dup2-bad-type.idio
	 *
	 * dup2 99 #t
	 */
	idio_error_param_type ("fixnum|C/int newfd", inewfd, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }


    int dup2_r = dup2 (C_oldfd, C_newfd);

    if (-1 == dup2_r) {
	/*
	 * Test Case: libc-wrap-errors/dup2-bad-fd.idio
	 *
	 * fd+name := mkstemp tmpfilename
	 * close (ph fd+name)
	 * delete-file (pht fd+name)
	 * dup2 (ph fd+name) 99
	 */
	idio_error_system_errno ("dup2", IDIO_LIST2 (ioldfd, inewfd), IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_int (dup2_r);
}

IDIO_DEFINE_PRIMITIVE1_DS ("dup", libc_dup, (IDIO oldfd), "oldfd", "\
in C, dup (oldfd)						\n\
a wrapper to libc dup(2)					\n\
								\n\
:param oldfd: file descriptor					\n\
:type oldfd: C/int or fixnum					\n\
:return: new fd or raises ^system-error				\n\
:rtype: C/int							\n\
")
{
    IDIO_ASSERT (oldfd);

    int C_oldfd = -1;
    if (idio_isa_fixnum (oldfd)) {
	C_oldfd = IDIO_FIXNUM_VAL (oldfd);
    } else if (idio_isa_C_int (oldfd)) {
	C_oldfd = IDIO_C_TYPE_int (oldfd);
    } else {
	/*
	 * Test Case: libc-wrap-errors/dup-bad-type.idio
	 *
	 * dup #t
	 */
	idio_error_param_type ("fixnum|C/int oldfd", oldfd, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    int dup_r = dup (C_oldfd);

    if (-1 == dup_r) {
	/*
	 * Test Case: libc-wrap-errors/dup-bad-fd.idio
	 *
	 * fd+name := mkstemp tmpfilename
	 * close (ph fd+name)
	 * delete-file (pht fd+name)
	 * dup (ph fd+name)
	 */
	idio_error_system_errno ("dup", oldfd, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_int (dup_r);
}

IDIO_DEFINE_PRIMITIVE1_DS ("close", libc_close, (IDIO ifd), "fd", "\
in C, close (fd)						\n\
a wrapper to libc close(2)					\n\
								\n\
:param fd: file descriptor					\n\
:type fd: C/int							\n\
:return: 0 or raises ^system-error				\n\
:rtype: C/int							\n\
")
{
    IDIO_ASSERT (ifd);

    /*
     * Test Case: libc-wrap-errors/close-bad-type.idio
     *
     * close #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, ifd);
    int C_fd = IDIO_C_TYPE_int (ifd);

    int close_r = close (C_fd);

    if (-1 == close_r) {
	/*
	 * Test Case: libc-wrap-errors/close-bad-fd.idio
	 *
	 * fd+name := mkstemp tmpfilename
	 * close (ph fd+name)
	 * delete-file (pht fd+name)
	 * close (ph fd+name)
	 */
	idio_error_system_errno ("close", ifd, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_int (close_r);
}

IDIO_DEFINE_PRIMITIVE1_DS ("chdir", libc_chdir, (IDIO path), "path", "\
in C, chdir (path)						\n\
a wrapper to libc chdir(2)					\n\
								\n\
:param path: directory name					\n\
:type path: string						\n\
:return: 0 or raises ^system-error				\n\
:rtype: C/int							\n\
")
{
    IDIO_ASSERT (path);

    /*
     * Test Case: libc-wrap-errors/chdir-bad-type.idio
     *
     * chdir #t
     */
    IDIO_USER_TYPE_ASSERT (string, path);
    size_t size = 0;
    char *C_path = idio_string_as_C (path, &size);
    size_t C_size = strlen (C_path);
    if (C_size != size) {
	/*
	 * Test Case: libc-wrap-errors/chdir-bad-format.idio
	 *
	 * chdir (join-string (make-string 1 #U+0) '("hello" "world"))
	 */
	IDIO_GC_FREE (C_path);

	idio_libc_format_error ("chdir: path contains an ASCII NUL", path, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    int chdir_r = chdir (C_path);

    IDIO_GC_FREE (C_path);

    if (-1 == chdir_r) {
	/*
	 * Test Case: libc-wrap-errors/chdir-non-existent.idio
	 *
	 * tmpdir := (make-tmp-dir)
	 * rmdir tmpdir
	 * chdir tmpdir
	 */
	idio_error_system_errno ("chdir", idio_S_nil, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    return idio_C_int (chdir_r);
}

IDIO_DEFINE_PRIMITIVE2_DS ("access", libc_access, (IDIO pathname, IDIO mode), "pathname mode", "\
in C, access (pathname, mode)					\n\
a wrapper to libc access(2)					\n\
								\n\
:param pathname: file name					\n\
:type pathname: string						\n\
:param mode: accessibility check(s)				\n\
:type mode: C/int						\n\
:return: #t or #f						\n\
:rtype: boolean							\n\
")
{
    IDIO_ASSERT (pathname);
    IDIO_ASSERT (mode);

    /*
     * Test Case: libc-wrap-errors/access-bad-pathname-type.idio
     *
     * access #t #t
     */
    IDIO_USER_TYPE_ASSERT (string, pathname);

    size_t size = 0;
    char *C_pathname = idio_string_as_C (pathname, &size);
    size_t C_size = strlen (C_pathname);
    if (C_size != size) {
	/*
	 * Test Case: libc-wrap-errors/access-bad-format.idio
	 *
	 * access (join-string (make-string 1 #U+0) '("hello" "world")) libc/R_OK
	 */
	IDIO_GC_FREE (C_pathname);

	idio_libc_format_error ("access: pathname contains an ASCII NUL", pathname, IDIO_C_FUNC_LOCATION ());

	return idio_S_notreached;
    }

    /*
     * Test Case: libc-wrap-errors/access-bad-mode-type.idio
     *
     * access "." #t
     */
    IDIO_USER_C_TYPE_ASSERT (int, mode);
    int C_mode = IDIO_C_TYPE_int (mode);

    IDIO access_r = idio_S_false;

    if (0 == access (C_pathname, C_mode)) {
	access_r = idio_S_true;
    }

    IDIO_GC_FREE (C_pathname);

    return access_r;
}

void idio_libc_api_add_primitives ()
{
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_write);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_waitpid);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_unlink);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_uname);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_times);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_tcsetpgrp);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_tcsetattr);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_tcgetpgrp);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_tcgetattr);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_strsignal);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_strerror);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_stat);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_sleep);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_signal);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_setrlimit);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_setpgid);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_getpgid);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_rmdir);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_regfree);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_regexec);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_regerror);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_regcomp);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_read);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_pipe);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_mkstemp);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_mkdtemp);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_mkdir);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_kill);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_isatty);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_getsid);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_getrusage);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_getrlimit);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_getpid);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_getpgrp);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_getcwd);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_fork);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_fcntl);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_dup2);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_dup);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_close);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_chdir);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_access);

}

void idio_init_libc_api ()
{

    /* /usr/include/bits/resource.h */
    /* enum __rlimit_resource */
    /*
     * RLIMIT_* are (more portably re-)defined in
     * idio_libc_set_rlimit_names() in libc-wrap.c however the
     * generated header/Idio files will still reference these names
     */
#ifdef __rlimit_resource
    idio_module_export_symbol_value (idio_symbols_C_intern ("RLIMIT_CPU"), idio_C_uint (RLIMIT_CPU), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("RLIMIT_FSIZE"), idio_C_uint (RLIMIT_FSIZE), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("RLIMIT_DATA"), idio_C_uint (RLIMIT_DATA), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("RLIMIT_STACK"), idio_C_uint (RLIMIT_STACK), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("RLIMIT_CORE"), idio_C_uint (RLIMIT_CORE), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("__RLIMIT_RSS"), idio_C_uint (__RLIMIT_RSS), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("RLIMIT_NOFILE"), idio_C_uint (RLIMIT_NOFILE), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("__RLIMIT_OFILE"), idio_C_uint (__RLIMIT_OFILE), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("RLIMIT_AS"), idio_C_uint (RLIMIT_AS), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("__RLIMIT_NPROC"), idio_C_uint (__RLIMIT_NPROC), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("__RLIMIT_MEMLOCK"), idio_C_uint (__RLIMIT_MEMLOCK), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("__RLIMIT_LOCKS"), idio_C_uint (__RLIMIT_LOCKS), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("__RLIMIT_SIGPENDING"), idio_C_uint (__RLIMIT_SIGPENDING), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("__RLIMIT_MSGQUEUE"), idio_C_uint (__RLIMIT_MSGQUEUE), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("__RLIMIT_NICE"), idio_C_uint (__RLIMIT_NICE), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("__RLIMIT_RTPRIO"), idio_C_uint (__RLIMIT_RTPRIO), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("__RLIMIT_RTTIME"), idio_C_uint (__RLIMIT_RTTIME), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("__RLIMIT_NLIMITS"), idio_C_uint (__RLIMIT_NLIMITS), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("__RLIM_NLIMITS"), idio_C_uint (__RLIM_NLIMITS), idio_libc_module);
#endif	/* __rlimit_resource */

    /* /usr/include/bits/resource.h */
    /* enum __rusage_who */
#ifdef __rusage_who
    idio_module_export_symbol_value (idio_symbols_C_intern ("RUSAGE_SELF"), idio_C_int (RUSAGE_SELF), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("RUSAGE_CHILDREN"), idio_C_int (RUSAGE_CHILDREN), idio_libc_module);
    idio_module_export_symbol_value (idio_symbols_C_intern ("RUSAGE_THREAD"), idio_C_int (RUSAGE_THREAD), idio_libc_module);
#endif  /* __rusage_who */

    IDIO fgvi;

    /* /usr/include/sys/utsname.h */
    IDIO_SYMBOL_DEF ("sysname", sysname);
    IDIO_SYMBOL_DEF ("nodename", nodename);
    IDIO_SYMBOL_DEF ("release", release);
    IDIO_SYMBOL_DEF ("version", version);
    IDIO_SYMBOL_DEF ("machine", machine);

    fgvi = IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_struct_utsname_ref);
    IDIO_C_STRUCT_IDENT_DEF("struct utsname", libc_struct_utsname, fgvi);

    /* /usr/include/sys/times.h */
    IDIO_SYMBOL_DEF ("tms_utime", tms_utime);
    IDIO_SYMBOL_DEF ("tms_stime", tms_stime);
    IDIO_SYMBOL_DEF ("tms_cutime", tms_cutime);
    IDIO_SYMBOL_DEF ("tms_cstime", tms_cstime);

    fgvi = IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_struct_tms_ref);
    IDIO_C_STRUCT_IDENT_DEF("struct tms", libc_struct_tms, fgvi);

    /* /usr/include/bits/termios-struct.h */
    IDIO_SYMBOL_DEF ("c_iflag", c_iflag);
    IDIO_SYMBOL_DEF ("c_oflag", c_oflag);
    IDIO_SYMBOL_DEF ("c_cflag", c_cflag);
    IDIO_SYMBOL_DEF ("c_lflag", c_lflag);
    IDIO_SYMBOL_DEF ("c_line", c_line);
    IDIO_SYMBOL_DEF ("c_cc", c_cc);
    IDIO_SYMBOL_DEF ("c_ispeed", c_ispeed);
    IDIO_SYMBOL_DEF ("c_ospeed", c_ospeed);

    fgvi = IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_struct_termios_ref);
    IDIO_C_STRUCT_IDENT_DEF("struct termios", libc_struct_termios, fgvi);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_struct_termios_set);

    /* /usr/include/bits/stat.h */
    IDIO_SYMBOL_DEF ("st_dev", st_dev);
    IDIO_SYMBOL_DEF ("st_ino", st_ino);
    IDIO_SYMBOL_DEF ("st_nlink", st_nlink);
    IDIO_SYMBOL_DEF ("st_mode", st_mode);
    IDIO_SYMBOL_DEF ("st_uid", st_uid);
    IDIO_SYMBOL_DEF ("st_gid", st_gid);
    IDIO_SYMBOL_DEF ("st_rdev", st_rdev);
    IDIO_SYMBOL_DEF ("st_size", st_size);
    IDIO_SYMBOL_DEF ("st_blksize", st_blksize);
    IDIO_SYMBOL_DEF ("st_blocks", st_blocks);
    IDIO_SYMBOL_DEF ("st_atim", st_atim);
    IDIO_SYMBOL_DEF ("st_mtim", st_mtim);
    IDIO_SYMBOL_DEF ("st_ctim", st_ctim);

    /* specials */
    IDIO_SYMBOL_DEF ("st_atime", st_atime);
    IDIO_SYMBOL_DEF ("st_mtime", st_mtime);
    IDIO_SYMBOL_DEF ("st_ctime", st_ctime);

    fgvi = IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_struct_stat_ref);
    IDIO_C_STRUCT_IDENT_DEF("struct stat", libc_struct_stat, fgvi);

    /* /usr/include/bits/types/struct_timespec.h */
    IDIO_SYMBOL_DEF ("tv_sec", tv_sec);
    IDIO_SYMBOL_DEF ("tv_nsec", tv_nsec);

    fgvi = IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_struct_timespec_ref);
    IDIO_C_STRUCT_IDENT_DEF("struct timespec", libc_struct_timespec, fgvi);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_struct_timespec_set);

    /* /usr/include/bits/resource.h */
    IDIO_SYMBOL_DEF ("rlim_cur", rlim_cur);
    IDIO_SYMBOL_DEF ("rlim_max", rlim_max);

    fgvi = IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_struct_rlimit_ref);
    IDIO_C_STRUCT_IDENT_DEF("struct rlimit", libc_struct_rlimit, fgvi);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_struct_rlimit_set);

    /* /usr/include/bits/types/struct_timeval.h */
    /* tv_sec already declared */
    IDIO_SYMBOL_DEF ("tv_usec", tv_usec);

    fgvi = IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_struct_timeval_ref);
    IDIO_C_STRUCT_IDENT_DEF("struct timeval", libc_struct_timeval, fgvi);
    IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_struct_timeval_set);

    /* /usr/include/bits/types/struct_rusage.h */
    IDIO_SYMBOL_DEF ("ru_utime", ru_utime);
    IDIO_SYMBOL_DEF ("ru_stime", ru_stime);

    fgvi = IDIO_EXPORT_MODULE_PRIMITIVE (idio_libc_module, libc_struct_rusage_ref);
    IDIO_C_STRUCT_IDENT_DEF("struct rusage", libc_struct_rusage, fgvi);

}
