profiled :
	$(MAKE) PROFLAGS=-pg

coverage :
	$(MAKE) COVFLAGS="-fprofile-arcs -ftest-coverage"

# adding -DIDIO_DEBUG=3 to SAN_CFLAGS causes a memory leak in
# __vasprintf_internal ...

# AddressSanitizer integrates LeakSanitizer
asan sanitize-address :
	$(MAKE) SAN_CFLAGS="-fsanitize=address -g" SAN_LDFLAGS=-fsanitize=address

# -fsanitize=undefined is a check group which includes most suboptions
# (null, enum, ...), see
# https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html
ubsan sanitize-undefined :
	$(MAKE) SAN_CFLAGS="-fsanitize=undefined -g" SAN_LDFLAGS=-fsanitize=undefined

lean :
	$(MAKE) MAKE_LEAN=1

debug :
	$(MAKE) MAKE_DEBUG=1
	$(MAKE) -C $(EXTDIR)/json5/src $@
	$(MAKE) -C $(EXTDIR)/expect/src $@
	$(MAKE) -C $(EXTDIR)/empty/src $@
	$(MAKE) -C $(EXTDIR)/SRFI-14/src $@
ifneq ($(IDIO_LIBCURL_DEV),)
	$(MAKE) -C $(EXTDIR)/libcurl/src $@
endif
ifneq ($(IDIO_ZLIB_DEV),)
	$(MAKE) -C $(EXTDIR)/zlib/src $@
endif
ifneq ($(IDIO_SQLITE3_DEV),)
	$(MAKE) -C $(EXTDIR)/sqlite3/src $@
endif

test : local-install
	$(LI_BINDIR)/idio test

# ASAN only (really) works with libc malloc which then blows up with a
# list as long as your arm about leaked memory.  I can't identify
# where the libc malloc behaviour differs from IDIO_MALLOC.
#
# In the meanwhile, rely on valgrind and IDIO_MALLOC
verify: ;
	@echo -e "\n\n**** clean start\n\n"
	$(MAKE) dist-clean > /dev/null
	# this includes the bootstrap-build
	$(MAKE) all > /dev/null
	# post-dist-clean we have new source files...
	$(MAKE) all > /dev/null
	@echo -e "\n\n**** regular test\n\n"
	$(LI_BINDIR)/idio test
	$(MAKE) pre-compile
	@echo -e "\n\n**** regular pre-compile test\n\n"
	$(LI_BINDIR)/idio test
	$(MAKE) build-clean clean-pre-compile > /dev/null
	$(MAKE) lean > /dev/null
	@echo -e "\n\n**** lean test\n\n"
	$(LI_BINDIR)/idio test
	$(MAKE) pre-compile
	@echo -e "\n\n**** lean pre-compile test\n\n"
	$(LI_BINDIR)/idio test
	$(MAKE) build-clean clean-pre-compile > /dev/null
	ASAN_OPTIONS=log_path=idio-asan $(MAKE) sanitize-address > /dev/null
	# we can at least pick up on ASAN errors in the bootstrap
	@echo -e "\n\n**** ASAN test\n\n"
	$(LI_BINDIR)/idio zero-length
	$(MAKE) pre-compile
	# including loading cache files
	@echo -e "\n\n**** ASAN pre-compile test\n\n"
	$(LI_BINDIR)/idio zero-length
	$(MAKE) build-clean clean-pre-compile > /dev/null
	$(MAKE) debug > /dev/null
	@echo -e "\n\n**** debug test\n\n"
	$(LI_BINDIR)/idio test
	$(MAKE) pre-compile
	@echo -e "\n\n**** debug pre-compile test\n\n"
	$(LI_BINDIR)/idio test
	# run valgrind with the debug version as the output is more useful
	$(MAKE) clean-pre-compile
	@echo -e "\n\n**** valgrind test\n\n"
	valgrind --leak-check=full --show-leak-kinds=all --child-silent-after-fork=yes --log-file=idio-valgrind.%p $(LI_BINDIR)/idio test
	ls -l idio-valgrind.*

doc :
	rm -rf $(SRCKDOUTDIR)
	(cd .. ; kernel-autodoc src $(SRCKDOUTDIR))
	#cp $(SRCKDOUTDIR)/*_[ch].rst $(SRCDOCDIR)
	diff -w <(grep _[ch] $(SRCKDOUTDIR)/index.rst) <(grep _[ch] $(SRCDOCDIR)/index.rst | sed -e 's!.*/!!')
	make -C $(SRCDOCDIR) html text

