SHLIB_NAME	:= lib$(MOD_NAME).so

# dummy versions if Makefile.system doesn't exist yet
MODULE_SYSTEM_VERSION_MM	?= a.b
MODULE_SYSTEM_VERSION_M		?= a

# local install
MODULE_LI_LIBDIR	:= $(LI_LIBVERDIR)/$(MOD_NAME)
MODULE_LI_LIBVERDIR	:= $(MODULE_LI_LIBDIR)/$(MODULE_SYSTEM_VERSION_MM)
MODULE_LI_LIBARCHDIR	:= $(MODULE_LI_LIBVERDIR)/$(IDIO_SYSTEM_ARCH)

all : $(MODULE_LI_LIBARCHDIR)/$(SHLIB_NAME)

clean :
	rm -f *.o *.d *.so *.so.*
	rm -f $(MOD_NAME)-system.h Makefile.system

local-install : $(MODULE_LI_LIBARCHDIR)/$(SHLIB_NAME) \
		$(MODULE_LI_LIBVERDIR)/$(MOD_NAME).idio \
		$(MODULE_LI_LIBDIR)/latest | Makefile.system $(MODULE_LI_LIBVERDIR)

clean-local-install :
	rm -rf $(MODULE_LI_LIBDIR)

$(MODULE_LI_LIBARCHDIR)/$(SHLIB_NAME) : $(MODULE_LI_LIBARCHDIR)/$(SHLIB_NAME).${MODULE_SYSTEM_VERSION_M}
	ln -sf $^ $@

$(MODULE_LI_LIBARCHDIR) :
	mkdir -p $@

$(MODULE_LI_LIBARCHDIR)/$(SHLIB_NAME).${MODULE_SYSTEM_VERSION_M} : $(MODULE_LI_LIBARCHDIR)/$(SHLIB_NAME).${MODULE_SYSTEM_VERSION_MM}
	ln -sf $^ $@

$(MODULE_LI_LIBARCHDIR)/$(SHLIB_NAME).${MODULE_SYSTEM_VERSION_MM} : $(SHLIB_NAME).${MODULE_SYSTEM_VERSION_MM} | $(MODULE_LI_LIBARCHDIR)
	cp $^ $@

$(SHLIB_NAME).${MODULE_SYSTEM_VERSION_MM} : $(LIBOBJS) $(MOD_NAME)-module.o
ifeq ($(OS),NetBSD)
	# NetBSD doesn't like the Idio library having the same soname
	# as the real sqlite3 library (and will not look for the
	# symbols in the real library)
	$(CC) $(LDFLAGS) $(LD_DLFLAGS) $(COVFLAGS) -o $@ $^ $(LIBS)
else
	$(CC) $(LDFLAGS) $(LD_DLFLAGS) $(MODULE_LD_SONAME_FLAGS) $(COVFLAGS) -o $@ $^ $(LIBS)
endif

$(MODULE_LI_LIBVERDIR)/$(MOD_NAME).idio : $(MOD_NAME).idio
	cp $^ $@

$(MODULE_LI_LIBDIR)/latest : Makefile.system
	echo $(MOD_NAME)@${MODULE_SYSTEM_VERSION_MM} > $(MODULE_LI_LIBDIR)/latest

$(MOD_NAME)-module.d : $(MOD_NAME)-system.h

$(MOD_NAME)-system.h Makefile.system : $(UTILSDIR)/bin/gen-idio-system
	CC=${CC} $(UTILSDIR)/bin/gen-idio-system -M $(MOD_NAME)

ifneq ($(MAKECMDGOALS),clean)
-include $(deps)
endif
