HOSTNAME	:= $(shell uname -n)
OS		:= $(shell uname -s)
REV		:= $(shell uname -r)
ARCH		:= $(shell uname -m)
SHELL		:= bash

# sudo make system-install may not define PWD
PWD		?= $(shell pwd)

TOPDIR		?= $(abspath $(PWD)/..)

SRCDIR		?= $(TOPDIR)/src
BINDIR		?= $(TOPDIR)/bin
LIBDIR		?= $(TOPDIR)/lib
EXTDIR		?= $(TOPDIR)/ext
TESTSDIR	?= $(TOPDIR)/tests
UTILSDIR	?= $(TOPDIR)/utils

# local install
LI_TOPDIR	?= $(TOPDIR)/.local
LI_BINDIR	?= $(LI_TOPDIR)/bin
LI_SHLIBDIR	?= $(LI_TOPDIR)/lib
LI_LIBDIR	?= $(LI_TOPDIR)/lib/idio
LI_LIBVERDIR	?= $(LI_LIBDIR)/${IDIO_SYSTEM_VERSION_MM}

# user install
UI_TOPDIR	?= $(HOME)/.local
UI_BINDIR	?= $(UI_TOPDIR)/bin
UI_LIBDIR	?= $(UI_TOPDIR)/lib/idio
UI_LIBVERDIR	?= $(UI_LIBDIR)/${IDIO_SYSTEM_VERSION_MM}

DOCDIR		?= $(TOPDIR)/doc
SRCDOCDIR	:= $(DOCDIR)/src
SRCKDOUTDIR	:= $(SRCDOCDIR)/kernel-autodoc-out

sources		:= $(wildcard *.c)
objects		:= $(patsubst %.c,%.o,$(sources))
deps		:= $(patsubst %.c,%.d,$(sources))
isources	:= $(wildcard $(LIBDIR)/*.idio) $(wildcard $(LIBDIR)/bootstrap/*.idio)

ifdef MAKE_LEAN
CDEBUG		:= -O3 -UIDIO_DEBUG -UIDIO_VM_PROF ${FORTIFY_CFLAGS}
else ifdef MAKE_DEBUG
CDEBUG		:= -DIDIO_DEBUG=3 -g -DIDIO_VM_PROF
else
CDEBUG		:=
endif


PROFLAGS	:=
COVFLAGS	:=
CFLAGS		:= -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Wno-unused-function -fPIC -DIDIO_MALLOC $(CFLAGS) $(PROFLAGS) $(COVFLAGS) $(SAN_CFLAGS) $(CDEBUG) $(LIBFFI_INC)
LDFLAGS		:= $(PROFLAGS) $(COVFLAGS) $(SAN_LDFLAGS) $(LDFLAGS)
LIBS		:= $(LIBS)

ifeq ($(OS),Darwin)
LD_DLFLAGS	:= -dynamiclib -undefined dynamic_lookup
else
LD_DLFLAGS	:= -shared
endif

IDIO_LD_SONAME_FLAGS	:=
MODULE_LD_SONAME_FLAGS	:=

# Yes, I know there's an arithmetic shift left of a signed variable!
# XXX older compilers (gcc-4?) don't support the option
CFLAGS		:= $(CFLAGS) -Wno-shift-negative-value

ifeq ($(OS),Darwin)

LIBFFI_INCDIR	:= /usr/include/ffi
ifeq ($(wildcard ${LIBFFI_INCDIR}/.),)
XCODE_DIR	:= $(shell xcode-select -print-path)
# can have multiple installs so pick the "last"
LIBFFI_INCDIR	:= $(shell find ${XCODE_DIR} -type d -name ffi | tail -1)
endif

ifeq ($(REV),9.8.0)
# No -Wno-shift-negative-value option
CFLAGS		:=
endif

LDFLAGS		:= -rdynamic
LIBS		:= -ldl

else ifeq ($(OS),Linux)

LIBFFI_INCDIR	= $(wildcard /usr/lib*/libffi-*/include)
LDFLAGS		:= -rdynamic
LIBS		:= -ldl

IDIO_LD_SONAME_FLAGS	:= -Wl,-soname=libidio.so.${IDIO_SYSTEM_VERSION_M}
MODULE_LD_SONAME_FLAGS	:= -Wl,-soname=lib${MODULE_NAME}.so.${MODULE_SYSTEM_VERSION_M}

ifeq ($(ARCH),x86_64)
CFLAGS		:= -m64 $(CFLAGS) # -fsanitize=undefined
LDFLAGS		:= -m64 -Wl,-Map=map $(LDFLAGS)
endif

ifeq (,$(wildcard /etc/os-release))

# CentOS 6 doesn't have /etc/os-release
ifneq (,$(findstring .el6.,$(REV)))
LIBS		:= -lrt $(LIBS)
endif

else

ID		:= $(shell grep ^ID= /etc/os-release)
VERSION_ID	:= $(shell grep ^VERSION_ID= /etc/os-release)

ifeq (ID=debian,$(ID))
ifneq (,$(findstring 10,$(VERSION_ID)))
# Careful: also includes RPi4 in 64-bit?
ifeq (,$(wildcard /etc/apt/sources.list.d/raspi.list))
CC		:= gcc-8
endif
endif
endif

ifeq (ID=ubuntu,$(ID))
ifneq (,$(findstring 18,$(VERSION_ID)))
ifeq (,$(findstring WSL2,$(REV)))
ifeq (,$(findstring Microsoft,$(REV)))
CC		:= gcc-8
endif
endif
endif
endif

endif

else ifeq ($(OS),SunOS)

VER		:= $(shell uname -v)

# OpenIndiana Development (pre-OpenIndiana Hipster)
ifneq (,$(findstring oi_,$(VER)))
# No -Wno-shift-negative-value option
CFLAGS		:=
endif

CC		:= gcc
LIBFFI_INCDIR	= $(wildcard /usr/lib/$(shell isainfo -k | grep -v i386)/libffi-*/include)
LDFLAGS		:= -L/usr/local/lib -R/usr/local/lib
LIBS		:= -ldl
CFLAGS		:= -D_POSIX_PTHREAD_SEMANTICS -D__EXTENSIONS__ $(CFLAGS)

IDIO_LD_SONAME_FLAGS	:= -Wl,-soname=libidio.so.${IDIO_SYSTEM_VERSION_M}
MODULE_LD_SONAME_FLAGS	:= -Wl,-soname=lib${MODULE_NAME}.so.${MODULE_SYSTEM_VERSION_M}

# Oracle Solaris 11.4
ifneq (,$(wildcard /etc/os-release))

# -D__XPG7_THREAD_MODEL__ is used because the macro isdigit() suggests
# ℏ is a digit.  The function variant is OK.

CFLAGS		:= -D__USE_DRAFT6_PROTOTYPES__ -D__XPG7_THREAD_MODEL__ $(CFLAGS)
endif

M64		:= $(filter %64, $(shell isainfo))
ifeq ($(M64),amd64)
CFLAGS		:= -m64 $(CFLAGS)
LDFLAGS		:= -m64 $(LDFLAGS)
endif

else ifeq ($(OS),FreeBSD)

ifeq ($(REV),10.0-RELEASE)
CC		:= $(wildcard /usr/local/bin/gcc4?)
else
CC		:= cc		# clang
endif

LIBFFI_INCDIR	:= /usr/local/include
LDFLAGS		:= -Xlinker --export-dynamic -L/usr/local/lib

IDIO_LD_SONAME_FLAGS	:= -Wl,--soname=libidio.so.${IDIO_SYSTEM_VERSION_M}
MODULE_LD_SONAME_FLAGS	:= -Wl,--soname=lib${MODULE_NAME}.so.${MODULE_SYSTEM_VERSION_M}

else ifeq ($(OS),OpenBSD)

CC		:= cc		# clang

LIBFFI_INCDIR	:= /usr/local/include
LDFLAGS		:= -Xlinker --export-dynamic -L/usr/local/lib

IDIO_LD_SONAME_FLAGS	:= -Wl,--soname=libidio.so.${IDIO_SYSTEM_VERSION_M}
MODULE_LD_SONAME_FLAGS	:= -Wl,--soname=lib${MODULE_NAME}.so.${MODULE_SYSTEM_VERSION_M}

CFLAGS		:= -DIDIO_DEV_FD $(CFLAGS)

else ifeq ($(OS),NetBSD)

CC		:= gcc

LDFLAGS		:= -Xlinker --export-dynamic -L/usr/local/lib

IDIO_LD_SONAME_FLAGS	:= -Wl,--soname=libidio.so.${IDIO_SYSTEM_VERSION_M}
MODULE_LD_SONAME_FLAGS	:= -Wl,--soname=lib${MODULE_NAME}.so.${MODULE_SYSTEM_VERSION_M}

CFLAGS		:= -DIDIO_DEV_FD $(CFLAGS)

endif

ifndef LIBFFI_INCDIR
$(warning WARNING: LIBFFI_INCDIR is unset)
LIBFFI_INC	:=
else
ifeq "$(LIBFFI_INCDIR)" ""
LIBFFI_INC	:=
else
LIBFFI_INC	:= -I$(LIBFFI_INCDIR)
endif
endif

lib%.so : %.o
	$(CC) -shared -o $@ $^

%.d: %.c
	@echo $@: $?
	@$(CC) -MM -MP -MF $@ $(CFLAGS) -I$(SRCDIR) $< -MT $*.o -MT $@
